### ISSUE TITLE
 Can you made the RxBleDeviceIml class implement the Parceable interface ?

### ISSUE THREAD

**Issue by CreaterXu** [Polidea/RxAndroidBle#101]
### Summary
<br />
#### Preconditions
<br />
#### Steps to reproduce actual result
1.
2.
3.
#### Actual result
<br />
#### Expected result
<br />

**Comment by dariuszseweryn** [comment]
Hello @CreaterXu 
Unfortunately it is not possible. At least not without a big amount of work.
You can try to get a reference to a proper `RxBleDevice` by calling `RxBleClient.getDevice(String)` and only store the device MAC address. I don't know your use case. You can ask a question on stackoverflow with a tag `rxandroidble` if you will need help with the code.
Best Regards
