### ISSUE TITLE
ProGuard configuration

### ISSUE THREAD

**Issue by mars3142** [Polidea/RxAndroidBle#104]
It would be nice to have a ProGuard file for this library. I want to use ProGuard for my app and at the moment everything from this library can't be renamed.

**Comment by dariuszseweryn** [comment]
Hello. 
Thanks for the info. I have incorporated `rxJava` Proguard configuration. Works for me. In case of problems - reopen this issue. (Change should be available shortly in `1.2.0-SNAPSHOT`)
Best Regards.
