### ISSUE TITLE
ConnectionAlreadyEstablished Exception

### ISSUE THREAD

**Issue by odmitriv** [Polidea/RxAndroidBle#11]
If the connection for some reason already exists and method .establishConnection(context, true) is performed, I get an exception ConnectionAlreadyEstablished. Which strategy  recovery state of connectionObservable in this case?

**Comment by uKL** [comment]
Please have a look at [this example](https://github.com/Polidea/RxAndroidBle/blob/master/sample/src/main/java/com/polidea/rxandroidble/sample/example4_characteristic/CharacteristicOperationExampleActivity.java) where ConnectionSharingAdapter is used. Does it answer your question?
