### ISSUE TITLE
Autoconnect recommanded value

### ISSUE THREAD

**Issue by ClemMahe** [Polidea/RxAndroidBle#117]
### Summary
Hello, first of all this is not an issue so feel free to close it. 
Thanks for all the work done on this library. I'm really interested in using it as it could leverage a lot of pain. 
How ever even if I understand the theory of Autoconnect, which either try a single connection using direct connection or either wait for the device to be ready a little longer, I still don't get in which scenario i should use connectGatt or not to get maximum compatibility.
By experience, autoConnect=false works well is way faster than autoConnect=true. Also on some phones like Samsung A5, scan seems required with both autoConnect value otherwise connexion will fail.

So my question is : Do you have recommandation about autoConnect value ? 

Thanks a lot.

Regards,
Clement.

#### Preconditions
BLE peripheral.

#### Steps to reproduce actual result
1. Call "device.establishConnection(context, false)" or "device.establishConnection(context, true)"

#### Actual result
1) Autoconnect false -> quicker (~2s) but more chance to fail if peripheral not ready.
2) Autoconnect true-> quicker (~15s in some case) but more chance to fail if peripheral not ready.

#### Expected result
Successful connection :)

**Comment by dariuszseweryn** [comment]
The `autoConnect` value depends mostly on the use-case. Usually I want to connect to a device as soon as possible so I use `false` because it either succeed or fail in limited time (30 seconds).
`true` is better if you want to eventually connect to a device and it is not essential to the user to get the connection very soon.
I hope this answers your question.
Best Regards

**Comment by ClemMahe** [comment]
That's how i see it too but I got surprises with BLE & low-end devices. It seem that BLE does not like many connection/disconnection in a short interval : it makes serviceDiscovery fails sometimes.
Thanks @dariuszseweryn for your explaination.
