### ISSUE TITLE
Filter devices with ManufacturerData

### ISSUE THREAD

**Issue by Dionysios** [Polidea/RxAndroidBle#127]
### Summary
<br /> Hi, I am not sure if I missed somehow by the ScanBleDevices can only accept UUID as filter.
Is it possible to scan with other filters eg manufacturer data?
Thanks!
#### Preconditions
<br />   public abstract Observable<RxBleScanResult> scanBleDevices(@Nullable UUID... filterServiceUUIDs);
#### Steps to reproduce actual result
1.
2.
3.
#### Actual result
<br />
#### Expected result
<br />

**Comment by uKL** [comment]
Currently there is no such feature. Feel free to contribute :)

**Comment by dariuszseweryn** [comment]
Of course it is possible to filter the devices with the manufacturer data. The thing is you have to do it manually as the library has no built-in feature. ;) This state will probably change once the Lollipop scanning API will be supported. You can still contribute to it! #74 Best Regards.

**Comment by dariuszseweryn** [comment]
Just added the new scanning API to `1.3.0-SNAPSHOT`. Feel free to check it out.
