### ISSUE TITLE
Sample code and README.md should provide examples of use for long write operation

### ISSUE THREAD

**Issue by uKL** [Polidea/RxAndroidBle#140]
### Summary
Sample code and README.md should provide examples of use for long write operation

#### Actual result
No sample code and readme.
<br />
#### Expected result
Users are happy and can see how to use long write operations.
<br />

**Comment by dariuszseweryn** [comment]
Added with 29ad3526e24226cc6c0dc2a25e2d7ab1d3f4db8a
