### ISSUE TITLE
6.0.1 

### ISSUE THREAD

**Issue by ZhanR** [Polidea/RxAndroidBle#144]
### Summary
<br />
#### Preconditions
<br />
#### Steps to reproduce actual result
1.
2.
3.
#### Actual result
<br />
#### Expected result
<br />

**Comment by ZhanR** [comment]
, please support the 6.0.1? I didn't run on 5.1.0 problems, running on the 6.0.1 appeared onNotificationReceived method is not called and writeCharacteristic write not to go out

**Comment by uKL** [comment]
Hello ZhanR,

could you please update this issue with the template provided? Please provide preconditions and the steps to reproduce the issue.

The library supports android 4.3+ so you shouldn't have problems. Please feel free to reopen with updated description.
