### ISSUE TITLE
Where is the SNAPSHOT status and where to find them?

### ISSUE THREAD

**Issue by Xiadalei** [Polidea/RxAndroidBle#151]
Hi,
With the long write feature not included in the latest release, I found it's hard to get the status of SNAPSHOT, so what version snapshot currently is and where to find them?

I tried `compile 'com.polidea.rxandroidble:rxandroidble:1.2.0-SNAPSHOT'` with default jcenter setting and failed.

**Comment by dariuszseweryn** [comment]
Add `maven { url "https://oss.sonatype.org/content/repositories/snapshots" }` under `repositories`.

**Comment by dariuszseweryn** [comment]
And what do you mean by `status`?

**Comment by Xiadalei** [comment]
Version, location etc.
I do believe this issue is resolved.
