### ISSUE TITLE
Observable.Zip notification results with write commands

### ISSUE THREAD

**Issue by AmitShah** [Polidea/RxAndroidBle#154]
### Summary
I have a custom piece of hardware that acknowledges writes to characteristics via notifications.  Is it possible to perform a zip operation between a writeCharacteristic and notification?  I leveraged the CharacteristicOperationExampleActivity.java and I would like to accomplish something like the following:

```
notificationObservable = connectionObservable
                    .flatMap(rxBleConnection -> rxBleConnection.setupNotification(UUID.fromString(...)))
                    .doOnNext(not -> runOnUiThread(this::notificationHasBeenSetUp));
Observable.from(new String[]{"AT$INFO=?"}).concatMap(cmd->
  Observable.zip(
                    connectionObservable.flatMap(
                                rxBleConnection ->
                                        rxBleConnection.writeCharacteristic(
                                                characteristicUuid,
                                                HexString.hexToBytes(convertStringToHex(cmd)))),
                        notificationObservable.flatMap(no->no),
                        Pair::new)



            ).subscribe(resultOfCommands->{
                //convertHexToString(HexString.bytesToHex((byte[])resultOfCommands));

            }, error->{

            });
```
However, I never receive any bytes from the notificationObservable.  I am sort of new to javarx, and any help is greatly appreciated.

**Comment by dariuszseweryn** [comment]
Please post this question on Stackoverflow instead of here as this is a question about how to implement a solution - not an issue in the library. The knowledge that will be in the answer will be easier to reach for other people when it will be available on Stackoverflow.

**Comment by dariuszseweryn** [comment]
@AmitShah When posting on Stackoverflow - remember to add a tag `rxandroidble`
