### ISSUE TITLE
Why is "establishConnection()

### ISSUE THREAD

**Issue by RobLewis** [Polidea/RxAndroidBle#157]
Since updating to RxAndroidBle 1.2.0, Android Studio advises me that in this code: 
```
Subscription connectBle() {
        return this.bleDevice
                .establishConnection( asBleServiceRef, NO_AUTO_CONNECT ) 
                .subscribe( connSubscriber );
    }
```
`establishConnection` is deprecated. Why is this, and how do I fix it? It seems to have been working with no problems.

**Comment by uKL** [comment]
Hey, we've introduced a new method, where you don't have to provide the context. You can remove asBleServiceRef.
