### ISSUE TITLE
Update documentation of device.establishConnection()

### ISSUE THREAD

**Issue by RobLewis** [Polidea/RxAndroidBle#159]
### Summary
Since `device.establishConnection(context, false)` is deprecated, the documentation should be updated
<br />
#### Preconditions
version 1.1.0 -> 1.2.0
<br />

`device.establishConnection(context, false)` should be replaced by `device.establishConnection(false)`

I don't know whether other things need updating but thought I would mention this one.

**Comment by dariuszseweryn** [comment]
Thanks for noticing!
