### ISSUE TITLE
How to get an existing connection?

### ISSUE THREAD

**Issue by jaychang0917** [Polidea/RxAndroidBle#163]
Suppose the ble device is paired and connected by user manually, how can i get the existing connection to perform read/write instead call `establishConnection` to create a new connection? Thanks!

**Comment by uKL** [comment]
How do you see the connection to be established otherwise than by calling the establishConnection method? This question looks to be a good candidate to be posted to StackOverflow with *rxandroidble* tag.

**Comment by jaychang0917** [comment]
In settings -> Bluetooth -> paired device, it shows connected

**Comment by uKL** [comment]
This shows you the Classic Bluetooth connection status, which is independent of Bluetooth Low Energy. In this case, just use establishConnection.

**Comment by jaychang0917** [comment]
oh, I get it! btw, if i call `establishConnection` two times, it will create two connections or reuse the existing connection?

**Comment by uKL** [comment]
1. If you'd do this when another connection with the same device is active you'll get an error.
2. Check ConnectionSharingAdapter and our example project.

**Comment by jaychang0917** [comment]
Thanks!
