### ISSUE TITLE
writeCharacteristic write wrong value sometimes

### ISSUE THREAD

**Issue by jaychang0917** [Polidea/RxAndroidBle#168]
```java
bleConnection.writeCharacteristic(LIGHT_A_UUID, data)
      .subscribeOn(Schedulers.io())
      .observeOn(AndroidSchedulers.mainThread())
      .subscribe(
        charValue -> {
          Log.d(TAG, "Change eye color success");
        },
        error -> {
          closeBleConnection();
        });
```

The above function is used to change a light color, sometimes sending the same byte data but results different light color, have any idea?

**Comment by uKL** [comment]
We need more data. Did you try enabling logs? Please have a look at `RxBleLog` class and it's static methods.

Do you mean that the data that is sent out is different that you provide to a write function?

**Comment by dariuszseweryn** [comment]
Hello @jaychang0917 - do you reuse your `byte[] data`?

**Comment by dariuszseweryn** [comment]
No response - closing.
