### ISSUE TITLE
can't find ble device after a disconnect problem, running in Android background service

### ISSUE THREAD

**Issue by ingalvaror** [Polidea/RxAndroidBle#172]
### Summary
<br />
Hi, i have a ble device (badge) and im running the functionality of rxAndroidBle in a Service on Android, i can connect and send commands, but suddenly the badge disconnect itself, i have many problems:
How can i try to reconnect when this happens?

When the badge disconnects itself, I can not see it again in the Scan of the devices, so I cant connect again, it seems that the badge is disconnected, but the BLE stack is still connected which is why the badge never sees the disconnect and never goes Back in to advertise mode. How can I handle this? How can i correctly remove the connection and try to connect again?

If I have this running in a service, I have to do any additional step? Thanks

this is my code(MyApplication class):

    public static RxBleClient getRxBleClient(Context context) {
        MyApplication application = (MyApplication) context.getApplicationContext();
        return application.rxBleClient;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        mInstance = this;

        if (rxBleClient == null)
        {
            rxBleClient = RxBleClient.create(this);
        }

        System.out.println("oncreateApp");

    }

this is called every time i open the app(in onstartcommand i send a bundle on the service call to stop and refresh the connection of the device, can you tell me if its this correct?):

 Intent intent = new Intent(context, MyService.class);
        context.startService(intent);

this is the service:

    public static final String
    String characteristicID = "6e400002-b5a3-f393-e0a9-e50e24dcca9e";
    private UUID characteristicUuid;
    private RxBleClient rxBleClient;
    private Subscription scanSubscription;
    private PublishSubject<Void> disconnectTriggerSubject = PublishSubject.create();
    private Observable<RxBleConnection> connectionObservable;
    private RxBleDevice bleDevice;
    private String color;
    private String mac_address_paired = "";

    @Override
    public void onCreate() {
        super.onCreate();
        Log.d(TAG, "onCreate");

        characteristicUuid = UUID.fromString(characteristicID);

        rxBleClient = MyApplication.getRxBleClient(this);
    }

    @Override
    public int onStartCommand(final Intent intent, final int flags, final int startId) {
        super.onStartCommand(intent, flags, startId);

        Log.d(TAG, "onStartCommand");

        if (intent != null && intent.getStringExtra("refresh") != null) {

            if(!isConnected())
           connect();
        }

        if (intent != null && intent.getStringExtra("stop") != null) {

            triggerDisconnect();
            if (isScanning())
                scanSubscription.unsubscribe();

        return START_NOT_STICKY;
    }

    @Override
    public void onTaskRemoved(Intent rootIntent) {
        super.onTaskRemoved(rootIntent);
        if (isScanning())
            scanSubscription.unsubscribe();
        stopSelf();
    }

this is the code to pair and sendcommand, i search for the device name and call connect method with the macaddress:

    public void pairAndSendCommand() {

            scanSubscription = rxBleClient.scanBleDevices()
                    .observeOn(AndroidSchedulers.mainThread())
                    .doOnUnsubscribe(this::clearSubscription)
                    .subscribe(new Action1<RxBleScanResult>() {
                        @Override
                        public void call(RxBleScanResult rxBleScanResult) {

                            if (rxBleScanResult.getBleDevice().getName() != null) {
                                if (rxBleScanResult.getBleDevice().getName().contains("ble device")) {

                                    mac_address_paired = rxBleScanResult.getBleDevice().getMacAddress();
                                    scanSubscription.unsubscribe();
                                    connect();

                                }
                            }
                        }
                    }, new Action1<Throwable>() {
                        @Override
                        public void call(Throwable throwable) {
                            onScanFailure(throwable);
                        }
                    });
        
    }

    private void clearSubscription() {
        scanSubscription = null;
    }

    private boolean isScanning() {
        return scanSubscription != null;
    }

    private void onConnectionStateChange(RxBleConnection.RxBleConnectionState newState) {
        System.out.println(newState.toString());
    }

    private void onScanFailure(Throwable throwable) {

        if (throwable instanceof BleScanException) {
            handleBleScanException((BleScanException) throwable);
        }
    }

    private Observable<RxBleConnection> prepareConnectionObservable() {
        return bleDevice
                .establishConnection(getApplicationContext(), false)
                .takeUntil(disconnectTriggerSubject)
                // .compose(bindUntilEvent(PAUSE))
                .doOnUnsubscribe(this::triggerDisconnect)
                .compose(new ConnectionSharingAdapter());
    }

the ble device need a password before send the commands:

    private void sendPass() {

        if (isConnected()) {

            connectionObservable
                    .flatMap(rxBleConnection->rxBleConnection.writeCharacteristic(characteristicUuid, password))
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(bytes->{
                        onWriteSuccessPass();
                    }, this::onWriteFailure);
        }

    }

    public void connect() {

        bleDevice = MyApplication.getRxBleClient(getApplicationContext()).getBleDevice(mac_address_paired);

        bleDevice.observeConnectionStateChanges()
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(this::onConnectionStateChange);

        connectionObservable = prepareConnectionObservable();

        connectionObservable.subscribe(rxBleConnection->{
            Log.d(getClass().getSimpleName(), "Hey, connection has been established!");
            sendPass();

        }, this::onConnectionFailure);

    }

    private boolean isConnected() {
        return bleDevice.getConnectionState() == RxBleConnection.RxBleConnectionState.CONNECTED;
    }

i verify the values of "color" and send the green or red light command:

    public void verifyColor() {
        if (color.equals("green")) {

            sendColor(green);

        } else if (color.equals("red")) {

            sendColor(red);
        }
    }

    public void sendColor(byte[] bytesColor) {
        if (isConnected()) {
            connectionObservable
                    .flatMap(rxBleConnection->rxBleConnection.writeCharacteristic(characteristicUuid, bytesColor))
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(bytes->{
                        onWriteSuccessPermission();
                    }, this::onWriteFailure);
        }
    }

the triggerDisconnect method is called when the ble device disconnect automatically, but i don't know if this need a additional step to remove the ble device and the device to be able to scan again, Thanks!
    private void triggerDisconnect() {
        disconnectTriggerSubject.onNext(null);
    }

**Comment by dariuszseweryn** [comment]
Looks like you have opened another topic #176 
Closing this one as it looks like a duplicate.
