### ISSUE TITLE
Can't connect to device again after disconnect

### ISSUE THREAD

**Issue by SsIDit** [Polidea/RxAndroidBle#177]
Can't connect to device again after disconnect.
<br />
The first time I connect to device everything is ok. Then I unsubscribe and when trying to connect again I get BleDisconnectedException and BleGattCannotStartException.
<br/>
Restarting bluetooth doesn't help. Only full recompile of app. When I connect without library, I don't have such problem.

**Log:**
```
04-19 17:49:24.197 4175-4175/com.nsofta.resmartbulb D/com.nsofta.resmartbulb.ble.SingleController: State changed: CONNECTING
04-19 17:49:24.303 4175-4175/com.nsofta.resmartbulb D/BluetoothGatt: connect() - device: 04:A3:16:A7:AD:5D, auto: false
04-19 17:49:24.303 4175-4175/com.nsofta.resmartbulb D/BluetoothGatt: registerApp()
04-19 17:49:24.303 4175-4175/com.nsofta.resmartbulb D/BluetoothGatt: registerApp() - UUID=e0225aec-28f1-4110-89bb-b397dad8a97c
04-19 17:49:24.305 4175-4186/com.nsofta.resmartbulb D/BluetoothGatt: onClientRegistered() - status=0 clientIf=5
04-19 17:49:25.533 4175-4187/com.nsofta.resmartbulb D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=5 device=04:A3:16:A7:AD:5D
04-19 17:49:25.536 4175-4417/com.nsofta.resmartbulb D/com.nsofta.resmartbulb.ble.SingleController: State changed: CONNECTED
04-19 17:49:25.552 4175-4417/com.nsofta.resmartbulb E/com.nsofta.resmartbulb.ble.SingleController: BleDisconnectedException{bluetoothDeviceAddress='04:A3:16:A7:AD:5D'}
04-19 17:49:25.565 4175-4175/com.nsofta.resmartbulb D/BluetoothGatt: discoverServices() - device: 04:A3:16:A7:AD:5D
04-19 17:49:26.660 4175-4253/com.nsofta.resmartbulb D/BluetoothGatt: onSearchComplete() = Device=04:A3:16:A7:AD:5D Status=0
04-19 17:49:26.661 4175-4417/com.nsofta.resmartbulb D/com.nsofta.resmartbulb.ble.SingleController: 
04-19 17:49:32.188 4175-4417/com.nsofta.resmartbulb E/com.nsofta.resmartbulb.ble.SingleController: BleDisconnectedException{bluetoothDeviceAddress='04:A3:16:A7:AD:5D'}
04-19 17:49:32.272 4175-4417/com.nsofta.resmartbulb E/com.nsofta.resmartbulb.ble.SingleController: BleDisconnectedException{bluetoothDeviceAddress='04:A3:16:A7:AD:5D'}
04-19 17:49:32.286 4175-4175/com.nsofta.resmartbulb E/com.nsofta.resmartbulb.ble.SingleController: BleGattCannotStartException{macAddress=04:A3:16:A7:AD:5D, bleGattOperationType=BleGattOperation{description='CHARACTERISTIC_WRITE'}}
04-19 17:49:32.303 4175-4175/com.nsofta.resmartbulb E/com.nsofta.resmartbulb.ble.SingleController: BleGattCannotStartException{macAddress=04:A3:16:A7:AD:5D, bleGattOperationType=BleGattOperation{description='CHARACTERISTIC_WRITE'}}
```

**Comment by dariuszseweryn** [comment]
Hello @SsIDit 
Please be so kind to show your code and call `RxBleLog.setLogLevel(RxBleLog.VERBOSE)` before capturing logs.

**Comment by SsIDit** [comment]
Hi, I did this before I posted this logs

Code:
```
    @Provides
    @Singleton
    public RxBleClient provideBleClient(Context context) {
        RxBleClient rxBleClient = RxBleClient.create(context);
        if (BuildConfig.DEBUG) {
            rxBleClient.setLogLevel(RxBleLog.VERBOSE);
        }
        return rxBleClient;
    }
```

**Comment by dariuszseweryn** [comment]
Then you are not posting logs from a debug build as there are clearly no logs from the library. Without it I cannot help you.
I will also need your code that is touching all interaction with the library.

**Comment by SsIDit** [comment]
Sorry for being so noob. I didn't check VERBOSE filter flag while watching logs. Here's full log:

`D/BluetoothAdapter: stopLeScan()
D/BluetoothAdapter: STATE_ON
D/RxBle#Radio:   QUEUED RxBleRadioOperationConnect(168601508)
D/RxBle#Radio:  STARTED RxBleRadioOperationConnect(168601508)
V/RxBle#BleConnectionCompat: Connecting without reflection
D/BluetoothGatt: connect() - device: 04:A3:16:A7:AD:5D, auto: false
D/BluetoothGatt: registerApp()
D/BluetoothGatt: registerApp() - UUID=df2acb44-52b4-4441-8cea-8aa69061a6f7
D/BluetoothGatt: onClientRegistered() - status=0 clientIf=5
D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=5 device=04:A3:16:A7:AD:5D
D/RxBle#BluetoothGatt: onConnectionStateChange newState=2 status=0
D/RxBle#Radio:   QUEUED RxBleRadioOperationServicesDiscover(11251770)
D/RxBle#Radio: FINISHED RxBleRadioOperationConnect(168601508)
D/RxBle#Radio:  STARTED RxBleRadioOperationServicesDiscover(11251770)
D/BluetoothGatt: discoverServices() - device: 04:A3:16:A7:AD:5D
D/BluetoothGatt: onSearchComplete() = Device=04:A3:16:A7:AD:5D Status=0
D/RxBle#BluetoothGatt: onServicesDiscovered status=0
D/RxBle#Radio: FINISHED RxBleRadioOperationServicesDiscover(11251770)
D/RxBle#Radio:   QUEUED RxBleRadioOperationCharacteristicWrite(8621495)
D/RxBle#Radio:  STARTED RxBleRadioOperationCharacteristicWrite(8621495)
D/RxBle#Radio:   QUEUED RxBleRadioOperationCharacteristicWrite(109083823)
D/RxBle#Radio:  REMOVED RxBleRadioOperationCharacteristicWrite(109083823)
D/RxBle#Radio:  STARTED RxBleRadioOperationCharacteristicWrite(119559651)
D/RxBle#BluetoothGatt: onCharacteristicWrite characteristic=0000ffe9-0000-1000-8000-00805f9b34fb status=0
D/RxBle#Radio: FINISHED RxBleRadioOperationCharacteristicWrite(119559651)
D/RxBle#Radio:   QUEUED RxBleRadioOperationDisconnect(41808438)
D/RxBle#Radio:  STARTED RxBleRadioOperationDisconnect(41808438)
V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@6a86e28
V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@2374741
D/RxBle#Radio:   QUEUED RxBleRadioOperationScan(266842456)
D/BluetoothManager: getConnectionState()
D/BluetoothManager: getConnectedDevices
D/BluetoothGatt: cancelOpen() - device: 04:A3:16:A7:AD:5D
D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=5 device=04:A3:16:A7:AD:5D
D/RxBle#BluetoothGatt: onConnectionStateChange newState=0 status=0
D/BluetoothGatt: close()
D/BluetoothGatt: unregisterApp() - mClientIf=5
D/RxBle#Radio: FINISHED RxBleRadioOperationDisconnect(41808438)
D/RxBle#Radio:  STARTED RxBleRadioOperationScan(266842456)
D/BluetoothAdapter: startLeScan(): null
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5
D/RxBle#Radio: FINISHED RxBleRadioOperationScan(266842456)
D/BluetoothAdapter: stopLeScan()
D/BluetoothAdapter: STATE_ON
D/RxBle#Radio:   QUEUED RxBleRadioOperationScan(45418503)
D/RxBle#Radio:  STARTED RxBleRadioOperationScan(45418503)
D/RxBle#Radio:   QUEUED RxBleRadioOperationScan(108427424)
D/BluetoothAdapter: startLeScan(): null
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=6
D/BluetoothAdapter: stopLeScan()
D/BluetoothAdapter: STATE_ON
D/RxBle#Radio: FINISHED RxBleRadioOperationScan(45418503)
D/RxBle#Radio:  STARTED RxBleRadioOperationScan(108427424)
D/BluetoothAdapter: startLeScan(): null
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=6
D/RxBle#Radio: FINISHED RxBleRadioOperationScan(108427424)
D/BluetoothAdapter: stopLeScan()
D/BluetoothAdapter: STATE_ON
D/RxBle#Radio:   QUEUED RxBleRadioOperationConnect(232084268)
D/RxBle#Radio:  STARTED RxBleRadioOperationConnect(232084268)
D/RxBle#Radio:   QUEUED RxBleRadioOperationCharacteristicWrite(29412271)
V/RxBle#BleConnectionCompat: Connecting without reflection
D/BluetoothGatt: connect() - device: 04:A3:16:A7:AD:5D, auto: false
D/BluetoothGatt: registerApp()
D/BluetoothGatt: registerApp() - UUID=70c2ac66-68f2-4146-bb05-696c14c2c50b
D/BluetoothGatt: onClientRegistered() - status=0 clientIf=6
D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=6 device=04:A3:16:A7:AD:5D
D/RxBle#BluetoothGatt: onConnectionStateChange newState=2 status=0
D/RxBle#Radio:   QUEUED RxBleRadioOperationServicesDiscover(83457778)
D/RxBle#Radio: FINISHED RxBleRadioOperationConnect(232084268)
D/RxBle#Radio:  STARTED RxBleRadioOperationCharacteristicWrite(29412271)
D/RxBle#Radio: FINISHED RxBleRadioOperationCharacteristicWrite(29412271)
E/com.nsofta.resmartbulb.ble.SingleController: BleGattCannotStartException{macAddress=04:A3:16:A7:AD:5D, bleGattOperationType=BleGattOperation{description='CHARACTERISTIC_WRITE'}}
D/RxBle#Radio:  STARTED RxBleRadioOperationServicesDiscover(83457778)
D/BluetoothGatt: discoverServices() - device: 04:A3:16:A7:AD:5D
D/BluetoothGatt: onSearchComplete() = Device=04:A3:16:A7:AD:5D Status=0
D/RxBle#BluetoothGatt: onServicesDiscovered status=0
D/RxBle#Radio: FINISHED RxBleRadioOperationServicesDiscover(83457778)
D/RxBle#Radio:   QUEUED RxBleRadioOperationCharacteristicWrite(128877050)
D/RxBle#Radio:  STARTED RxBleRadioOperationCharacteristicWrite(128877050)
E/com.nsofta.resmartbulb.ble.SingleController: BleGattCannotStartException{macAddress=04:A3:16:A7:AD:5D, bleGattOperationType=BleGattOperation{description='CHARACTERISTIC_WRITE'}}
D/RxBle#Radio: FINISHED RxBleRadioOperationCharacteristicWrite(128877050)
D/RxBle#Radio:   QUEUED RxBleRadioOperationCharacteristicWrite(50847623)
D/RxBle#Radio:  STARTED RxBleRadioOperationCharacteristicWrite(50847623)
E/com.nsofta.resmartbulb.ble.SingleController: BleGattCannotStartException{macAddress=04:A3:16:A7:AD:5D, bleGattOperationType=BleGattOperation{description='CHARACTERISTIC_WRITE'}}`

First time I discover devices, connect to one of them. Then I do some operations (I removed logs, that repeat). Sometimes you can see - REMOVED, it's because I send many commands at a short period of time so I need to unsubscribe before send new command. Then I disconnect from device, start scan again and connect to it again. Trying to send command again gives me BleGattCannotStartException

Here's code of my controller class:

`import android.bluetooth.BluetoothGattCharacteristic;
import android.bluetooth.BluetoothGattService;
import android.graphics.Color;
import android.util.Log;

import com.nsofta.resmartbulb.ApplicationLoader;
import com.nsofta.resmartbulb.Logger;
import com.nsofta.resmartbulb.database.model.Bulb;
import com.nsofta.resmartbulb.database.model.Function;
import com.nsofta.resmartbulb.database.model.Mood;
import com.nsofta.resmartbulb.database.model.Timer;
import com.nsofta.resmartbulb.utils.ByteUtils;
import com.nsofta.resmartbulb.utils.ColorUtils;
import com.polidea.rxandroidble.RxBleClient;
import com.polidea.rxandroidble.RxBleConnection;
import com.polidea.rxandroidble.RxBleDevice;

import java.lang.reflect.Field;
import java.util.Calendar;
import java.util.List;

import javax.inject.Inject;

import rx.Subscription;
import rx.functions.Action1;

import static android.R.attr.type;

public class SingleController implements BulbController {

    public static final String LOG_TAG = SingleController.class.getName();

    @Inject
    protected RxBleClient bleClient;

    private Bulb bulb;
    private RxBleDevice device;
    private RxBleConnection connection;
    private BluetoothGattCharacteristic dataCharacterisctic;

    private Subscription connSubscription;
    private Subscription connStateSubscription;
    private Subscription commandSubscription;
    private Subscription serviceDiscoverSubscription;

    private Action1<byte[]> onSuccess = o -> {
    };
    private Action1<Throwable> onThrowable = throwable -> Logger.logError(LOG_TAG, throwable);

    public SingleController(Bulb bulb) {
        ApplicationLoader.getBleComponent().add(this);
        this.bulb = bulb;
        this.device = bleClient.getBleDevice(bulb.address);
    }

    @Override
    public void connect(boolean autoConnect, ConnectionListener listener) {
        connStateSubscription = device.observeConnectionStateChanges().subscribe(connState -> {
            String state = getConnectionState(connState);
//            Log.d(LOG_TAG, "State changed: " + state);
            switch (state) {
                case "DISCONNECTED":
                    break;
            }
        });
        connSubscription = device.establishConnection(autoConnect)
                .subscribe(
                        rxBleConnection -> {
                            Log.d(LOG_TAG, "Got connection");
                            this.connection = rxBleConnection;
                            serviceDiscoverSubscription = rxBleConnection.discoverServices().subscribe(
                                    result -> {
                                        Log.d(LOG_TAG, "Got services: " + result.getBluetoothGattServices().toString());
                                        if (listener != null) {
                                            listener.onConnected(bulb);
                                        }
                                        analyzeGat(result.getBluetoothGattServices());
                                    },
                                    t -> {
                                        if (listener != null) {
                                            listener.onError(t);
                                        }
                                    });
                        },
                        t -> {
                            if (listener != null) {
                                listener.onError(t);
                            }
                        });
    }

    @Override
    public void disconnect() {
        if (serviceDiscoverSubscription != null && !serviceDiscoverSubscription.isUnsubscribed()) {
            serviceDiscoverSubscription.unsubscribe();
        }
        if (connSubscription != null && !connSubscription.isUnsubscribed()) {
            connSubscription.unsubscribe();
        }
        if (connStateSubscription != null && !connStateSubscription.isUnsubscribed()) {
            connStateSubscription.unsubscribe();
        }
    }

    @Override
    public void setColor(int color) {
        if (dataCharacterisctic == null) return;
        if (type == Bulb.LED_STRIP) {
            unsubscribeLast();
            commandSubscription = connection.writeCharacteristic(dataCharacterisctic, new byte[]{0x56, 0, 0, 0, 0, (byte) 0x0F, (byte) 0xAA}).subscribe(
                    writeBytes -> setColorOld(color),
                    onThrowable
            );
        } else {
            setColorOld(color);
        }
    }

    @Override
    public void setWarm(byte level) {
        if (dataCharacterisctic == null) return;

        if (type == Bulb.LED_STRIP) {
            int color = ColorUtils.getColorWithBrightness(Color.BLACK, 0);
            byte red = (byte) Color.red(color);
            byte green = (byte) Color.green(color);
            byte blue = (byte) Color.blue(color);
            unsubscribeLast();
            commandSubscription = connection.writeCharacteristic(dataCharacterisctic, new byte[]{0x56, red, green, blue, (byte) 255, (byte) 0xF0, (byte) 0xAA}).subscribe(
                    writeBytes -> setWarmOld(level),
                    onThrowable
            );
        } else {
            setWarmOld(level);
        }
    }

    @Override
    public void turnOn() {
        if (dataCharacterisctic == null) return;
        unsubscribeLast();
        commandSubscription = connection.writeCharacteristic(dataCharacterisctic, new byte[]{(byte) 0xCC, 0x23, 0x33}).subscribe(
                onSuccess, onThrowable
        );
    }

    @Override
    public void turnOff() {
        if (dataCharacterisctic == null) return;
        unsubscribeLast();
        commandSubscription = connection.writeCharacteristic(dataCharacterisctic, new byte[]{(byte) 0xCC, 0x24, 0x33}).subscribe(
                onSuccess, onThrowable
        );
    }

    @Override
    public void askState() {
        if (dataCharacterisctic == null) return;
        unsubscribeLast();
        commandSubscription = connection.writeCharacteristic(dataCharacterisctic, new byte[]{(byte) 0xEF, 0x01, 0x77}).subscribe(
                onSuccess, onThrowable
        );
    }


    @Override
    public void setFunction(Function function, byte speed) {
        if (dataCharacterisctic == null) return;
        unsubscribeLast();
        commandSubscription = connection.writeCharacteristic(dataCharacterisctic, new byte[]{(byte) 0xBB, function.data, speed, 0x44}).subscribe(
                onSuccess, onThrowable
        );
    }

    @Override
    public void setMood(Mood mood) {
        if (dataCharacterisctic == null) return;
        unsubscribeLast();
        commandSubscription = connection.writeCharacteristic(dataCharacterisctic, mood.data).subscribe(
                onSuccess, onThrowable
        );
    }

    @Override
    public void setTimers(List<Timer> timers) {
        if (dataCharacterisctic == null) return;

        byte[] data = new byte[(ByteUtils.TIMERS_IN_COMMAND * ByteUtils.TIMER_SIZE) + 3];
        data[0] = 0x23;
        for (int i = 0; i < timers.size(); i++) {
            Timer timer = timers.get(i);
            if ((type == Bulb.LED_OLD || type == Bulb.LED_STRIP) && timer.state.sun != null) {
                ByteUtils.fill(ByteUtils.TIMER_DISABLED_BYTES, data, (i * ByteUtils.TIMER_SIZE) + 1);
            } else {
                byte[] timerBytes = ByteUtils.parseTimerToBytes(timer);
                ByteUtils.fill(timerBytes, data, (i * ByteUtils.TIMER_SIZE) + 1);
            }
        }
        for (int i = timers.size(); i < ByteUtils.TIMERS_IN_COMMAND; i++) {
            ByteUtils.fill(ByteUtils.TIMER_DISABLED_BYTES, data, (i * ByteUtils.TIMER_SIZE) + 1);
        }
        data[(ByteUtils.TIMERS_IN_COMMAND * ByteUtils.TIMER_SIZE) + 1] = 0x0;
        data[(ByteUtils.TIMERS_IN_COMMAND * ByteUtils.TIMER_SIZE) + 2] = 0x32;

        unsubscribeLast();
        commandSubscription = connection.writeCharacteristic(dataCharacterisctic, data).subscribe(
                onSuccess, onThrowable
        );
    }

    @Override
    public void askTimers() {
        if (dataCharacterisctic == null) return;
        unsubscribeLast();
        commandSubscription = connection.writeCharacteristic(dataCharacterisctic, new byte[]{0x24, 0x2A, 0x2B, 0x42}).subscribe(
                onSuccess, onThrowable
        );
    }

    @Override
    public void setTime(Calendar calendar) {
        if (dataCharacterisctic == null) return;
        byte weekDayByte = 0;
        byte dayOfWeek = (byte) ((calendar.get(Calendar.DAY_OF_WEEK) - 1));
        if (dayOfWeek == 0) dayOfWeek = 7;
        weekDayByte = ByteUtils.setBit(weekDayByte, 8 - dayOfWeek);
        unsubscribeLast();
        commandSubscription = connection.writeCharacteristic(dataCharacterisctic, new byte[]{0x10, 0x14,
                (byte) (calendar.get(Calendar.YEAR) - 2000), (byte) (calendar.get(Calendar.MONTH) + 1),
                (byte) calendar.get(Calendar.DAY_OF_MONTH), (byte) calendar.get(Calendar.HOUR_OF_DAY),
                (byte) calendar.get(Calendar.MINUTE), (byte) calendar.get(Calendar.SECOND), weekDayByte, 0x0, 0x01}).subscribe(
                onSuccess, onThrowable
        );
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Bulb other = ((SingleController) o).bulb;
        return other.equals(bulb);
    }

    @Override
    public int hashCode() {
        return bulb.hashCode();
    }

    private void analyzeGat(List<BluetoothGattService> bluetoothGattServices) {
        for (BluetoothGattService bls : bluetoothGattServices) {
            List<BluetoothGattCharacteristic> characteristics = bls.getCharacteristics();
            for (BluetoothGattCharacteristic bch : characteristics) {
                if (bls.getUuid().toString().contains("ffe5")
                        && bch.getUuid().toString().contains("ffe9")) {
                    dataCharacterisctic = bch;
                    dataCharacterisctic.setWriteType(BluetoothGattCharacteristic.WRITE_TYPE_DEFAULT);
                }

                if (bls.getUuid().toString().contains("ffe0")
                        && bch.getUuid().toString().contains("ffe4")) {
                    connection.setupNotification(bch);
                }
            }
        }
    }

    private void setColorOld(int color) {
        byte red = (byte) Color.red(color);
        byte green = (byte) Color.green(color);
        byte blue = (byte) Color.blue(color);
        unsubscribeLast();
        commandSubscription = connection.writeCharacteristic(dataCharacterisctic, new byte[]{0x56, red, green, blue, (byte) 255, (byte) 0xF0, (byte) 0xAA})
                .subscribe(onSuccess, onThrowable);
    }

    private void setWarmOld(byte level) {
        unsubscribeLast();
        commandSubscription = connection.writeCharacteristic(dataCharacterisctic, new byte[]{0x56, 0, 0, 0, level, (byte) 0x0F, (byte) 0xAA})
                .subscribe(onSuccess, onThrowable);
    }

    //abort previous command
    private void unsubscribeLast() {
        if (commandSubscription != null && !commandSubscription.isUnsubscribed()) {
            commandSubscription.unsubscribe();
        }
    }

    private String getConnectionState(RxBleConnection.RxBleConnectionState state) {
        try {
            Field field = RxBleConnection.RxBleConnectionState.class.getDeclaredField("description");
            field.setAccessible(true);
            return (String) field.get(state);
        } catch (IllegalAccessException e) {
            Logger.logError(LOG_TAG, e);
        } catch (NoSuchFieldException e) {
            Logger.logError(LOG_TAG, e);
        }
        return "undefined";
    }
}`

**Comment by SsIDit** [comment]
It seems to me, that problem is in discovering services. From documentation of library:

> Result of the discovery is cached internally so consecutive calls won't trigger BLE operation

Are there any ways to force clearing services cache?

**Comment by dariuszseweryn** [comment]
Force – currently not unless you will do it yourself in a custom operation.

I see that you are not managing the state of the connection and you may be using an old `RxBleConnection` before new is established.

**Comment by SsIDit** [comment]
I just moved 
```
if (serviceDiscoverSubscription != null && !serviceDiscoverSubscription.isUnsubscribed()) {
                        serviceDiscoverSubscription.unsubscribe();
                    }
                    if (connStateSubscription != null && !connStateSubscription.isUnsubscribed()) {
                        connStateSubscription.unsubscribe();
                    }
```

in doOnUnsubscribe method of my establishConnection() subscription and everything worked.
Thank you so much! I could't solve this issue for a week. You've made me happy. Issue is solved.

**Comment by dariuszseweryn** [comment]
Glad to help.
