### ISSUE TITLE
Patterns for a Mock Device to hold state and return values 

### ISSUE THREAD

**Issue by jdebner** [Polidea/RxAndroidBle#192]
Thanks for this awesome library!

We are using a mock device to allow our app to work without actually connecting to a device. Our device receives commands on one command characteristic then writes back responses to our app on a different notify characteristic. 

I've tried from within our app when sending a command, writing the response back to the expected characteristic using the device connection but because that write is coming from the client rather than the "fake device" the subscriber for incoming notifications never triggers.

I think you do something similar to what I want to do in your groovy test but I couldn't quite parse out where you would create your observables for commands sent from the app to certain device characteristics and how to write back as if it was from the device.

I think adding a little more information on mocking out devices like these in the readme or documentation could also be really helpful.

```
def "should return notification data"() {
        given:
        def testSubscriber = TestSubscriber.create()
        rxBleClient.scanBleDevices(null)
                .take(1)
                .map { scanResult -> scanResult.getBleDevice() }
                .flatMap { rxBleDevice -> rxBleDevice.establishConnection(false) }
                .flatMap { rxBleConnection -> rxBleConnection.setupNotification(characteristicNotifiedUUID) }
                .subscribe { obs -> obs.map { data -> new String(data) } subscribe(testSubscriber) }

        when:
        characteristicNotificationSubject.onNext("NotificationData".getBytes())

        then:
        testSubscriber.assertValue("NotificationData")
    }
```

**Comment by uKL** [comment]
I think this should be closed in favor of #370. Feel free to reopen if you think otherwise.
