### ISSUE TITLE
Memory leak on RxBleInternalScanResult for long scanning period

### ISSUE THREAD

**Issue by lukevr** [Polidea/RxAndroidBle#194]
### Summary
<br />
Objects RxBleInternalScanResult are not collected by GC, in case when phone scans for a long time. The speed of scanning(e.g. passing rxBleScanResult to subscriber) goes down dramatically. 

#### Preconditions
<br />

Long lastScanTime = 0;

Subscription scanSubscription = rxBleClient.scanBleDevices()
	.subscribe(
	    rxBleScanResult -> {
               // Process scan result here.
               long currTime = currentTimeMillis();
               Log.i(TAG, "Delay between results: " + (currTime - lastScanTime));
               lastScanTime = currTime;
	    },
	    throwable -> {
	        // Handle an error here.
	    }
	);

#### Steps to reproduce actual result
1.  3-5 BLE services should advertise in one room,  Run App, keep Activity active.
2. See unexpected "Delay between results" after 15-20 min in Logcat
3. See continues growing of RxBleInternalScanResult objects in Dumped Java Heaps

#### Actual result
<br />

The amount of RxBleInternalScanResult keeps growing, the performance of scanning goes down.

#### Expected result
<br />

GC collects old RxBleInternalScanResult, the performance of scanning is stable.

**Comment by dariuszseweryn** [comment]
Fixed with b53d84065657af07e380e5aaf9b4a6d73b064000 
Should be available in `1.2.3-SNAPSHOT` shortly and in `1.2.3` later today.
