### ISSUE TITLE
Add a helper for retrieving data from byte[]

### ISSUE THREAD

**Issue by dariuszseweryn** [Polidea/RxAndroidBle#199]
### Summary
<br />
The `BluetoothGattCharacteristic` has methods like `getIntValue()`, `getFloatValue()` and `getStringValue`.
Provide a helper for retrieving that data from `byte[]` emitted by `.readCharacteristic()` or notifications.

**Comment by RobLewis** [comment]
I use the standard Java class [ByteBuffer](http://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html): it wraps a byte[] and does exactly this.
