### ISSUE TITLE
Suggest to add a method for the "getConnectedDevices"

### ISSUE THREAD

**Issue by ZacharyTech** [Polidea/RxAndroidBle#200]
Hello, I suggest you add a function "getConnectedDevices" to the RxBleClient class inside the project, this method is used to connect the device  
[See](https://developer.android.com/reference/android/bluetooth/BluetoothManager.html#getConnectedDevices(int))

**Comment by dariuszseweryn** [comment]
Hello @ZacharyTech 
Could you describe what would you need this feature for? You can now track state of individual `RxBleDevice`s via `.observeConnectionStateChanges()`.

**Comment by ZacharyTech** [comment]
Use the phone settings -> Bluetooth connection device (BLE device + Android phone), then it will not be able to scan this device.
As long as the standard BLE equipment can be used to connect the above way!

This question is actually a supplement to [How to get an existing connection](https://github.com/Polidea/RxAndroidBle/issues/163)

**Comment by dariuszseweryn** [comment]
AFAIK the Settings -> Bluetooth shows only Bluetooth Classic devices which is not directly related to BLE connection and you would still need to establish it.

**Comment by ZacharyTech** [comment]
I am sure it is BLE, using the device is  [DIJ OSMO Mobile](http://www.dji.com/osmo-mobile/info) + Samsung S6.

**Comment by dariuszseweryn** [comment]
Ok. Neverthless what would you expect from the suggested method? You can already get all connected devices via `BluetoothAdapter.getDefaultAdapter().getConnectedDevices()`

**Comment by ZacharyTech** [comment]
Although through the `BluetoothAdapter.getDefaultAdapter (). GetConnectedDevices ()` can be obtained to the connected device，but i don't know  how to associate it with `RxAndridBle` and operate it!

**Comment by dariuszseweryn** [comment]
You can use `BluetoothDevice.getAddress()` which returns the Bluetooth Mac Address String and then use `RxBleClient.getBleDevice(bluetoothMacAddressString)`. There is nothing more that can be done.

**Comment by ZacharyTech** [comment]
How to read or write, I use `RxBleClient.getBleDevice (macAddress) .establishConnection (autoConnect) `will appear `BleAlreadyConnectedException`

**Comment by dariuszseweryn** [comment]
You must have already established the connection to your device via calling `.establishConnection()`.
You have to manage your connection and unsubscribe from `.establishConnection()` when you want the connection to be closed.
For more information check out the samples, documentation and Stackoverflow for tag `rxandroidble`.

**Comment by ZacharyTech** [comment]
Okay, thank you very much.

**Comment by dariuszseweryn** [comment]
You are welcome. Closing.
