### ISSUE TITLE
Read ACTION_STATE_CHANGED ?

### ISSUE THREAD

**Issue by baadillahnabil** [Polidea/RxAndroidBle#201]
hi, i'm still learning this, but how can i know when users turn off their bluetooth and do something about it or when users turn on their bluetooth. in regular way is checking ACTION_STATE_CHANGED , but i don't know how to do that with this library

Thank you before for this great library, really really helpful ;)

**Comment by dariuszseweryn** [comment]
Hello @baadillahnabil 
If you would search this repository for phrase `ACTION_STATE_CHANGED` you would find a public class: `RxBleAdapterStateObservable` which should do exactly what you want.

**Comment by baadillahnabil** [comment]
oh ya i found it now, thank you, i wasn't able to find that (my bad), thanks again

**Comment by dariuszseweryn** [comment]
No problem. :) I will give it more visibility by adding a hint on the Readme page.

**Comment by baadillahnabil** [comment]
cool, thanks for that too :)
