### ISSUE TITLE
Error message：BleCannotSetCharacteristicNotificationException{bluetoothGattCharacteristic=XXXXX····}

### ISSUE THREAD

**Issue by edifangyi** [Polidea/RxAndroidBle#202]
### I can write information via Demo, but I can not listen to the information my device has sent
<br />
I get through a lot of BLEDemo to UUID, for example
<br />

service：0003cdd0-0000-1000-8000-00805f9b0131
notify：0003cdd1-0000-1000-8000-00805f9b0131
write：0003cdd2-0000-1000-8000-00805f9b0131
<br />
In other Demo can be heard on the equipment to send the data can also be written. But in this project, I can only write, can not notify
<br />
I have not changed the project code.
<br />
I do not know whether it is a Bluetooth chip.
<br />

Other Demo can be notify, this project can not
<br />

一加3T
7.1.1

**Comment by dariuszseweryn** [comment]
Hello @edifangyi 
Does your characteristic has a `PROPERTY_NOTIFY`?

**Comment by edifangyi** [comment]
@dariuszseweryn yes，，look here
![](http://ww1.sinaimg.cn/large/648b709cly1fg2hlyd68vj20u01hcgrf.jpg)

</br>
I clicked Notify  -> CONNECT - >REGISTER NOTIFICATIONS : 
</br>

BleCannotSetCharacteristicNotificationException{bluetoothGattCharacteristic=0003cdd1-0000-1000-8000-00805f9b0131}

**Comment by dariuszseweryn** [comment]
Does your notify characteristic have a Client Characteristic Config descriptor?

**Comment by edifangyi** [comment]
@dariuszseweryn I'm sorry, I did not read your meaning. However, I use the Bluetooth manufacturers to provide the Demo can use the monitor

http://ww1.sinaimg.cn/large/648b709cly1fg2i5uzpjsj20u01hcjsw.jpg

**Comment by dariuszseweryn** [comment]
I think that your characteristic (`0003cdd1-0000-1000-8000-00805f9b0131`) does not have a Client Characteristic Config descriptor (`00002902-0000-1000-8000-00805f9b34fb`) which causes the error.

If that is the case you could use function `RxBleConnection.setupNotification(UUID, NotificationSetupMode.COMPAT)`

**Comment by edifangyi** [comment]
@dariuszseweryn  Thank you, the problem is solved. I will ask the Bluetooth chip manufacturers in this area related issues

**Comment by Andy4ward** [comment]
@dariuszseweryn I've been looking into how i can call the RxBleConnection.setupNotifcation method from my react native project with very little success.

I can go into the android package and set all monitor notifcations to COMPAT but that just causes errors elsewhere.

Should it be possible to get to the the setupNotification function by importing NativeModules from React Native?

**Comment by dariuszseweryn** [comment]
@Andy4ward This issue should be now fixed in the RN library
