### ISSUE TITLE
App crashes when bluetooth is turned off during a scan start/stop cycle

### ISSUE THREAD

**Issue by chuks** [Polidea/RxAndroidBle#206]
### App crashes when bluetooth is turned off during a scan start/stop cycle
<br />
Steps to reproduce actual result: <br>
1. Start scanning<br>
2. Turn off bluetooth<br>
3. Stop scanning<br/><br>
Actual result:<br>
- App crashes because bluetoothAdapter is no longer available, so the library references a null object while trying to call bluetoothAdapter.getBluetoothLeScanner().stopScan(scanCallback);
<br /><br>
Expected result:<br>
The library should gracefully handle this case where the phone's bluetooth is turned off mid-cycle (which could be during a scan - start or stop, gatt write, gatt read, etc). I fixed this for the scan case in internal.util/RxBleAdapterWrapper.java by just wrapping all the method calls that reference bluetoothAdapter with: <br>
if (isBluetoothEnabled()) {...<add any reference to bluetoothAdapter call here>...
}

<br />

**Comment by uKL** [comment]
Hey,

could you post logs in a verbose mode?

**Comment by dariuszseweryn** [comment]
Recognized and done. Should be available in `1.3.0-SNAPSHOT` shortly.
