### ISSUE TITLE
Release 1.3.0?

### ISSUE THREAD

**Issue by kenwdelong** [Polidea/RxAndroidBle#209]
Just a quick question: any thoughts on the timeline for release 1.3.0?

**Comment by dariuszseweryn** [comment]
I would like to make it somewhere this week.

**Comment by dariuszseweryn** [comment]
@kenwdelong Feel free to test `1.3.0-SNAPSHOT` in the mean time. I do not expect any changes to the API but it would be easier to fix bugs before the release.

**Comment by kenwdelong** [comment]
That was my plan for today!!  :-)

**Comment by kenwdelong** [comment]
I've integrated the SNAPSHOT build, and so far so good.  We'll do some more extensive testing tomorrow.

BTW, why did you comment out setReportDelay() etc in ScanSettingsBuilder?

**Comment by dariuszseweryn** [comment]
Because that is not yet implemented in a backwards-compatible way. This is a place for pull requests from the community if anyone will need this functionality — from my experience implemented features are the most used ones.

**Comment by kenwdelong** [comment]
After a day of testing, so far everything is working fine.

**Comment by dariuszseweryn** [comment]
Good to hear that. I plan to make an official release today.

**Comment by dariuszseweryn** [comment]
Released.

**Comment by kenwdelong** [comment]
Excellent, thanks!
