### ISSUE TITLE
onConnectionStateChange only includes RxBleConnectionState, does not include status 

### ISSUE THREAD

**Issue by chuks** [Polidea/RxAndroidBle#214]
#### Steps to reproduce actual result
<br />1. Register a connection observable
<br />2. Connect to a ble device

#### Minimum code snippet reproducing the issue

         ` rxBleDevice.observeConnectionStateChanges()
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(this::onConnectionStateChange, this::onConnectionFailure);

            connectionObservable = rxBleDevice
                    .establishConnection(flag)
                    .takeUntil(disconnectTriggerSubject)
                    .doOnUnsubscribe(this::clearSubscription)
                    .unsubscribeOn(AndroidSchedulers.mainThread())
                    .compose(new ConnectionSharingAdapter());

            connectionObservable
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(this::onConnectionReceived, this::onConnectionFailure);
`
#### Logs from the application running with setting `RxBleLog.setLogLevel(RxBleLog.VERBOSE)`

           `D/RxBle#Radio:   QUEUED RxBleRadioOperationConnect(988092768)
             D/RxBle#Radio:  STARTED RxBleRadioOperationConnect(988092768)
             V/RxBle#BleConnectionCompat: Connecting without reflection
             D/BluetoothGatt: connect() - device: EC:7E:14:AF:0E:D5, auto: false
             D/BluetoothGatt: registerApp() 
             D/BluetoothGatt: registerApp() - UUID=0e257e89-8b1d-48a7-a1d4-0ffe49ac8a19
             D/BluetoothGatt: onClientRegistered() - status=0 clientIf=6
             D/BluetoothGatt: onClientConnectionState() - status=133 clientIf=6 device=EC:7E:14:AF:0E:D5
             D/RxBle#BluetoothGatt: onConnectionStateChange newState=0 status=133
             D/RxBle#Radio: FINISHED RxBleRadioOperationConnect(988092768)`

#### Expected result
Expect to be able to retrieve the status emitted from the native onClientConnectionState() via the library, which can be parsed in the onConnectionStateChange method. The library's onConnectionStateChange only includes RxBleConnectionState. 

There are certain instances were I'll need to handle a state change separately, if I get a status error of 133 or 129, etc.

**Comment by dariuszseweryn** [comment]
Hello @chuks 

I think that you are mixing `RxBleDevice.observeConnectionStateChanges()` with `BluetoothGattCallback.onConnectionStateChange()`.

The `RxBleDevice.observeConnectionStateChanges()` works as expected. It was designed as a convenience function for checking in what state is the specific device and use this information for i.e. displaying UI indication. 

If you need the information about what went wrong with the connection you need to listen to `RxBleDevice.establishConnection(boolean)` which will emit information about statuses in the `onError`.

There is currently a discussion on how the `RxBleDevice.observeConnectionStateChanges()` should work in #50 

Best Regards
