### ISSUE TITLE
Add possibility to get BluetoothDevice from RxBleDevice

### ISSUE THREAD

**Issue by pszklarska** [Polidea/RxAndroidBle#23]
It'll be helpful to have getter in RxBleDeviceImpl class for bluetoothDevice (e.g. for using combined BLE and classic Bluetooth)

**Comment by tatewaki** [comment]
This would be nice :+1: 

my Workaround is reflection:
<pre>
try {
    Field field = device.getClass().getDeclaredField("bluetoothDevice");
    field.setAccessible(true);
    BluetoothDevice nativeDevice = (BluetoothDevice) field.get(device);
    entry.setNativeDevice(nativeDevice);
} catch (Exception e) {
     e.printStackTrace();
}
</pre>

**Comment by dariuszseweryn** [comment]
Should be possible to use `RxBleDevice.getBluetoothDevice()` in the next snapshot of the library.
