### ISSUE TITLE
Can't find printer device.

### ISSUE THREAD

**Issue by ramanbranavitski** [Polidea/RxAndroidBle#247]
Hi there. I'am trying to find printer using your library and can't do it. I use following `scanSettings` and `scanFilter`. As a result I receive list of nearby mobiles and tablets, but printer isn't visible. How can I tackle my problem? Thanks.

`var scanSettings = ScanSettings.Builder()
                .setScanMode(ScanSettings.SCAN_MODE_BALANCED)
                .setCallbackType(ScanSettings.CALLBACK_TYPE_ALL_MATCHES)
                .build()`

`var scanFilter = ScanFilter.Builder()
                .build()`

**Comment by dariuszseweryn** [comment]
Hello @ramanbranavitski 
As far as I understand you are not reporting an issue with the library but you ask a question about the usage of scanning and filtering of Bluetooth Low Energy devices. 
Those questions and the knowledge held in the answers is easier to be found by other users on www.stackoverflow.com with a tag `rxandroidble`. Please post a question with appropriate tags there and someone will try to help you.
Best Regards

**Comment by dariuszseweryn** [comment]
[Reference](https://stackoverflow.com/questions/45057047/rxandroidble-work-with-not-low-energy-devices).
