### ISSUE TITLE
Please add possibility to use hidden metod refresh on BluetoothGatt

### ISSUE THREAD

**Issue by vibexie** [Polidea/RxAndroidBle#249]
Hello！If we do OAD to upgrade firmware and the characteristics of new firmware is different with the old firmware，it is very necessary to refresh the phone ble cache！

**Comment by dariuszseweryn** [comment]
Hello @vibexie
This issue is a duplicate to #53
You can find there how you can use the `.refresh()` method there. You could also share there your exact use-case — when you would like to execute the method — if it would at the beginning of a connection, on end or in the middle.
Best Regards
