### ISSUE TITLE
Get long Write Respons 

### ISSUE THREAD

**Issue by leof23** [Polidea/RxAndroidBle#258]
### Summary
Hi, I'm doing a long write to a BLE for making an OTA update, but I need to wait for the write response of the BLE device for sending more data but I don't know how to catch the device write response, I'm using a Samsung galaxy tab s2 with android 7, and Kotlin for my code

#### Long Write Code
```
    override fun otaDataWrite(data:ByteArray) {
        manager.connection?.flatMap { rxBleConnection: RxBleConnection? -> rxBleConnection?.createNewLongWriteBuilder()
                ?.setCharacteristicUuid(OTACharacteristics.OTA_DATA.uuid)
                ?.setBytes(data)
                ?.setMaxBatchSize(totalPackages)
                ?.build()
        }?.subscribe({ t: ByteArray? ->
            Log.i("arrive", "data ${converter.bytesToHex(t)}")
            manageOtaWrite()
        }, { t: Throwable? -> t?.printStackTrace() })
```
#### Actual result
every time that i write the characteristic the subscriptions respond me inmediatly with the written data
#### Expected result
i need capture the response of the characteristic, for sending more data

**Comment by dariuszseweryn** [comment]
Hello @leof23 
This is a question about the usage of the library. As it was written in [the disclaimer](https://github.com/Polidea/RxAndroidBle/blob/master/.github/ISSUE_TEMPLATE.md) these questions should be addressed on the [Stackoverflow with `rxandroidble` tag](https://stackoverflow.com/questions/tagged/rxandroidble) where the knowledge is more easily accessible for others.
Best Regards
