### ISSUE TITLE
Bluetooth Mesh

### ISSUE THREAD

**Issue by RobLewis** [Polidea/RxAndroidBle#267]
Probably something for the distant future, but I just learned about the existence of [Bluetooth Mesh](https://www.bluetooth.com/what-is-bluetooth-technology/how-it-works/le-mesh/case-mesh), which is a mesh network based on BLE. 

It will be interesting to learn more about it and whether it's something Polidea might consider supporting. There are of course other mesh networks in use now, so it should be interesting to see how BT Mesh compares.

**Comment by dariuszseweryn** [comment]
Thanks for bringing it up. We are aware of this new standard and we will see if/when it will be available in the Android API—we will evaluate this issue again then—currently we have enough on our plate to deal with. :) 👍
