### ISSUE TITLE
Unable to get observeStateChanges().switchMap work

### ISSUE THREAD

**Issue by Sundeep1501** [Polidea/RxAndroidBle#292]
### Disclaimer
Before you will post a new issue to the RxAndroidBle library consider if you are filling a bug/feature request or a general question 
about:
* Usage of RxJava
* Usage of Bluetooth Low Energy
* Usage of RxAndroidBle
* Weird behaviour of the peripheral you are using
* Other not directly related to a new feature request or a bug

If any of the above points seems to match your use case — consider using Google or creating a question on www.stackoverflow.com with 
a tag `rxandroidble` where it will be easier to access by other people with similar questions. Issues that are not bugs or feature requests
will be closed.

### Summary
I'm trying to implement observeStateChanges to know the ble state of the device then to scan.
Non of the RxBleClient.State is being called.

Sample Activity would really helpful on this method.
### Library version
`1.4.1`

#### Preconditions
Using rxjava2, Dagger2, kotlin
#### Steps to reproduce actual result
<br />1. Used the sample code available on the site page for observeStateChanges
<br />2. 
<br />3.
#### Minimum code snippet reproducing the issue

     flowSubscription = rxBleClient.observeStateChanges()
                .switchMap(state -> { // switchMap makes sure that if the state will change the rxBleClient.scanBleDevices() will unsubscribe and thus end the scan
                    switch (state) {

                        case READY:
                            // everything should work
                            return rxBleClient.scanBleDevices();
                        case BLUETOOTH_NOT_AVAILABLE:
                            // basically no functionality will work here
                        case LOCATION_PERMISSION_NOT_GRANTED:
                            // scanning and connecting will not work
                        case BLUETOOTH_NOT_ENABLED:
                            // scanning and connecting will not work
                        case LOCATION_SERVICES_NOT_ENABLED:
                            // scanning will not work
                        default:
                            return Observable.empty();
                    }
                })
                .subscribe(
                        rxBleScanResult -> {
                            // Process scan result here.
                            Log.i("Device found", "" + rxBleScanResult.getBleDevice().getMacAddress());
                        },
                        throwable -> {
                            // Handle an error here.
                            Log.i("Device found", "Error ");
                        }
                );

**Comment by dariuszseweryn** [comment]
Hello,

From the `Javadoc`:
```
    /**
     * Returns an observable emitting state _changes_ of the RxBleClient environment which may be helpful in deciding if particular
     * functionality should be used at a given moment.
     *
     * @see #getState() for {@link State} precedence order
     *
     * Examples:
     * - If the device is in {@link State#READY} and the user will turn off the bluetooth adapter then {@link State#BLUETOOTH_NOT_ENABLED}
     * will be emitted.
     * - If the device is in {@link State#BLUETOOTH_NOT_ENABLED} then changing state of Location Services will not cause emissions
     * because of the checks order
     * - If the device is in {@link State#BLUETOOTH_NOT_AVAILABLE} then this {@link Observable} will complete because any other checks
     * will not be performed as devices are not expected to obtain bluetooth capabilities during runtime
     *
     * To get the initial {@link State} and then observe changes you can use: `observeStateChanges().startWith(getState())`.
     *
     * @return the observable
     */
    public abstract Observable<State> observeStateChanges();
```

It clearly states: _changes_
You can use `.startWith(rxBleClient.getState())`.
