### ISSUE TITLE
Support API 26 ScanResult properties

### ISSUE THREAD

**Issue by radimvaculik** [Polidea/RxAndroidBle#300]
### Summary

Since API 26, there is an option to get connectable status on ScanResult via [ScanResult#isConnectable](https://developer.android.com/reference/android/bluetooth/le/ScanResult.html#isConnectable()). Unfortunately, there is no backport for older SDKs. Is there any plan to bump targetSdk to 26 and implement this feature to RxAndroidBle?

**Comment by dariuszseweryn** [comment]
Hello,
There are no plans for that yet. But PRs are welcome! :)

**Comment by radimvaculik** [comment]
See more information @ #668.
