### ISSUE TITLE
Introduce more verbose logging

### ISSUE THREAD

**Issue by uKL** [Polidea/RxAndroidBle#304]
Currently, the library mostly logs the state of the operations. This is helpful for debugging the library itself. Additionally, I think that we could have logs with:

- [x] Scan results
- [x] Applied scan filters
- [x] Service discovery result
- [x] Characteristics UUIDs
- [x] Hex dump of the data written & read
- [x] MTU change request details
- [x] Notification occurrences 
- [x] Details on checking the adapter, permissions, etc.

**Comment by RobLewis** [comment]
Bravo! Fantastic help for debugging. Would these be output to separate files, and/or logcat? I assume there would be an API for choosing options—maybe just a bitfield? 

Maybe include connection state changes, if not already covered.

**Comment by uKL** [comment]
Related to #367 on the API level.

**Comment by dariuszseweryn** [comment]
Released in `1.9.0`
