### ISSUE TITLE
android devices not emitted by ScanBleDevices

### ISSUE THREAD

**Issue by ndrdmarshmallow** [Polidea/RxAndroidBle#307]
I am using the example1 to list the available Bluetooth devices. But I am not getting android devices, Mac devices.

is there anything I am missing ??

Thanks in advance

**Comment by uKL** [comment]
Hey, 

thanks for using the library!

For questions about usage please select one of the desired options

- non-commercial — head to StackOverflow tag #rxandroidble
- commercial — drop an email to hello@polidea.com for more info
