### ISSUE TITLE
Replace Android Groovy Plugin workaround with a new plugin version

### ISSUE THREAD

**Issue by uKL** [Polidea/RxAndroidBle#309]
With Gradle 3.0.0 there's an issue with compatibility with Groovy (https://github.com/groovy/groovy-android-gradle-plugin/issues/156).

Currently, @mapyo [introduced](https://github.com/Polidea/RxAndroidBle/pull/302) a workaround in `rxandroidble/build.gradle`. Once the new version of Groovy plugin is released it would be good to bump it in our code and get rid of the workaround.

**Comment by dariuszseweryn** [comment]
I think this may be closed now with the plugin in version 2.0.0.

**Comment by uKL** [comment]
:+1:
