### ISSUE TITLE
Huawi P9 connection problems.

### ISSUE THREAD

**Issue by RobartGmbH** [Polidea/RxAndroidBle#316]
### Summary
I am using the library in my project and in general works fine. However, today we managed to find a device Huawei P9, android 7.0, to which we cannot connect at all.
We always get the BleDisconnectedException.
E.g: BleDisconnectedException{bluetoothDeviceAddress='64:CF:D9:2B:39:B1'}

### Library version
`1.4.2`

#### Steps to reproduce actual result
Try to connect to a Huawei P9 device.

#### Minimum code snippet reproducing the issue
```
> return RxJavaInterop.toV2Flowable(rxBleDevice.establishConnection(false))
                          .observeOn(AndroidSchedulers.mainThread())
                          .delay(5, TimeUnit.SECONDS)
                          .doOnNext(conn -> connection = conn)
                          .flatMap(new Function<RxBleConnection, Publisher<Observable<byte[]>>>() {
                                 @Override
                                 public Publisher<Observable<byte[]>> apply(@NonNull RxBleConnection conn) throws Exception {
                                      return    RxJavaInterop.toV2Flowable(connection.setupNotification(UUID.fromString(notifyCharacteristic)))
                                                          .observeOn(AndroidSchedulers.mainThread())
                                                          **problem happens here** 
```

I debugged a lot this and it seems a disconnect is triggered somewhere because in your library, class RxBleDeviceImpl - isConnected is set to false during the setupConnection call.
 
```
> return connector.prepareConnection(options)
>                             .doOnUnsubscribe(new Action0() {
>                                 @Override
>                                 public void call() {
>                                     isConnected.set(false); <- **this is called during setupConnection**
>                                 }
>                             });
```

#### Logs from the application running with setting RxBleLog.setLogLevel(RxBleLog.VERBOSE)
```             
> exception:cc.robart.bluetooth.sdk.exceptions.RobBleCoreException:   BleDisconnectedException{bluetoothDeviceAddress='64:CF:D9:2B:39:B1'}
```
we wrap the exception in onErrorResume method

#### Actual result
It does not connect.

#### Expected result

It should connect.

If I am doing something wrong, please let me know. However this configuration works fine on the following devices:

 -  Samsung Galaxy S7 Edge
 -  Samsung S6
 -  Moto G2
 -  Pixel
 -  OnePlus

**Comment by dariuszseweryn** [comment]
Hello,

Thanks for using our library!

This does not seem to be a bug in the library itself because as you have mentioned the code works on other devices. If you need support:
* non-commercial—head to StackOverflow tag `rxandroidble`
* commercial—drop an email to hello@polidea.com for more info
