### ISSUE TITLE
setupNotification cause extra memory allocation

### ISSUE THREAD

**Issue by andyalbert** [Polidea/RxAndroidBle#331]
I've noticed a strange behaviour in android profiler after registering for notifications, the java memory keeps increasing so fast allocating hundreds of objects per second (it reached 120 thousand in 3 minutes)!
I've attached an image for heap dump
![screenshot from 2017-11-30 22 21 27](https://user-images.githubusercontent.com/12417645/33453037-d8cd3c64-d61c-11e7-8bd1-6d04d9fa3661.png)

**Comment by dariuszseweryn** [comment]
Hello,
Do you say that the allocations are strange or the memory allocated is not released?

**Comment by andyalbert** [comment]
I mean that the memory allocation keeps increasing till it forces a GC action, is that usual ?

**Comment by passsy** [comment]
That's a normal behavior of the JVM. It's not possible to release objects without the GC.

**Comment by dariuszseweryn** [comment]
Well, yes- each notification received is packed into an object and emitted. If those objects are deallocated by the GC then everything is ok.

**Comment by andyalbert** [comment]
Hmm, so that's just a usual behaviour as the ble device is sending a lot of data, that describes the problem then, Thanks! , but regarding the notification itself, why is it passing `Observable<Observable<byte[]>>` instead of just `Observable<byte[]>`? I thought either the notification should send a stream of data, or either the data(`byte[]`) itself be streamed, but both?

**Comment by dariuszseweryn** [comment]
From the Javadoc of `RxBleConnection.setupNotification()`:
```
     * Setup characteristic notification in order to receive callbacks when given characteristic has been changed. Returned observable will
     * emit Observable<byte[]> once the notification setup has been completed. 
```
This means that the emitted `Observable<byte[]>` is an object that will stream the notification byte arrays. But setting up the notification is also an asynchronous process and takes time.

**Comment by andyalbert** [comment]
Thanks a lot, it's all clear now.
