### ISSUE TITLE
Need to write multiple commands on device 1 by 1 

### ISSUE THREAD

**Issue by usman-afzal** [Polidea/RxAndroidBle#351]
Its taking too long to write a single command on characteristics. I am using below code for a single command and a loop on it.
```
getConnObservable()
  .first()
  .flatMap(rxBleConnection -> rxBleConnection.writeCharacteristic(characteristics, command))
  .observeOn(AndroidSchedulers.mainThread())
  .subscribe(
    bytes -> onWriteSuccess(),
    this::onWriteFailure
  );
```
Its taking almost 600ms to write on device. I need to write like 100 of commands 1 by 1.

Can anyone please explain what is the best way to do that batch operation

**Comment by dariuszseweryn** [comment]
Hello!

Thank you for using the library.

This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rxandroidble) with `rxandroidble` tag—it will be easier to find by other users.

Best Regards
