### ISSUE TITLE
Indication getting processed before CharacteristicReadOperation completes.

### ISSUE THREAD

**Issue by jayalfredprufrock** [Polidea/RxAndroidBle#359]
### Summary
I'm working with a peripheral that requires reading an arbitrary amount of data from a particular characteristic. It requires subscribing to an indication that lets the device know when data is ready to process. When this indication is received, the device issues a read request. When the peripheral has detected that the data has been read, if there is more data available it sends another indication and the process continues. When I review the log of processed operations, I can see that subsequent indications are received and processed before the read operation completes. This peripheral is well tested and I see no such behavior in implementations on other platforms. It would seem to be a bug, unless Android / RxAndroidBle doesn't guarantee the order of notifications/indications versus the ConnectionOperationQueue.

To prove that this wasn't an issue with the peripheral, I was able to add a delay to the peripheral code after processing the read request but before sending the indication that more data was available. I started with 50ms which is safely above the established connection interval (~40ms). This would guarantee that the read request is fully processed before the indication is ever sent. I found that adding this delay made the first read request complete before the second indication, however the second read request came after the third indication as before. I raised the delay to 100ms and was able to see a few more properly ordered events before things got behind again. It wasn't until I raised the delay to 500ms that the order of events was correct and consistent. 

I plan on doing another experiment using notifications instead of indications, however I'm hoping somebody can let me know if I'm making an invalid assumption about how RxAndroidBle works.

### Library version
`1.4.3`

#### Preconditions
If a peripheral sends a notification immediately after it processes a read request, the notification is received _before_ the read request is completed.

#### Minimum code snippet reproducing the issue
I'm using fairly vanilla code to subscribe to the indication and read the characteristic, taken right out of the examples. Happy to paste that code here if that helps.

#### Logs from the application running with setting `RxBleLog.setLogLevel(RxBleLog.VERBOSE)`
```
14:54:52.878 D/RxBle#BluetoothGatt: onCharacteristicChanged characteristic=6175726f-7261-49ce-8077-b954b033c881
14:54:52.910 D/RxBle#ConnectionOperationQueue:   QUEUED CharacteristicReadOperation(50921439)
14:54:52.912 D/RxBle#ConnectionOperationQueue:  STARTED CharacteristicReadOperation(50921439)
14:54:53.141 D/RxBle#BluetoothGatt: onCharacteristicChanged characteristic=6175726f-7261-49ce-8077-b954b033c881
14:54:53.142 D/RxBle#BluetoothGatt: onCharacteristicRead characteristic=6175726f-7261-49ce-8077-b954b033c880 status=0
14:54:53.151 D/RxBle#ConnectionOperationQueue: FINISHED CharacteristicReadOperation(50921439)
14:54:53.153 D/RxBle#ConnectionOperationQueue:   QUEUED CharacteristicReadOperation(215570667)
14:54:53.154 D/RxBle#ConnectionOperationQueue:  STARTED CharacteristicReadOperation(215570667)
14:54:53.399 D/RxBle#BluetoothGatt: onCharacteristicRead characteristic=6175726f-7261-49ce-8077-b954b033c880 status=0
14:54:53.402 D/RxBle#ConnectionOperationQueue: FINISHED CharacteristicReadOperation(215570667)
```
#### Actual result

The second `onCharacteristicChanged` comes before `onCharacteristicRead` and thus before the CharacteristicReadOperation(50921439) finishes.

#### Expected result

I would expect the `onCharacteristicChanged` to come after the read operation completes, since the indication is sent by the peripheral after it finishes processing the read request.

**Comment by dariuszseweryn** [comment]
Hello @jayalfredprufrock 

Thank you for using the library!

As you can see in the log above the native of `BluetoothGattCallback.onCharacteristicChanged()` has been called before `BluetoothGattCallback.onCharacteristicRead()`. It means that in this order the native Android BLE stack has processed those events. It is possible that those events have been transmitted on-air in different order but for that we would need to sniff the BLE packets.

Either way there is no possibility for the library to tell what should be the correct order of the native callbacks.

It should be possible to handle this scenario on the application side. If you would need support you can find more info [here](https://github.com/Polidea/RxAndroidBle#support).

Best Regards
