### ISSUE TITLE
GATT exception 

### ISSUE THREAD

**Issue by yusufonderd** [Polidea/RxAndroidBle#360]
### Summary
I'm getting this exception when read characteristic : 

> GATT exception from MAC address 0C:F3:EE:2A:ED:49, status 137, type BleGattOperation{description='CHARACTERISTIC_READ'}. (Look up status 0x89 here https://android.googlesource.com/platform/external/bluetooth/bluedroid/+/android-5.1.0_r1/stack/include/gatt_api.h)

### Library version
`1.4.3`
#### Minimum code snippet reproducing the issue

```
if (device.connectionState == RxBleConnection.RxBleConnectionState.CONNECTED) {
                rxConnection.readCharacteristic(ConstantsBle.deviceUUIDCharacteristic).subscribe({
                   Log.e(TAG,"read characteristic task is success")
                }, {
                    it.printStackTrace()
                })
        }
```

**Comment by dariuszseweryn** [comment]
Hello!

Thank you for using the library.

This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rxandroidble) with `rxandroidble` tag—it will be easier to find by other users.

Best Regards
