### ISSUE TITLE
When I write data to the device, the device is automatically disconnected.

### ISSUE THREAD

**Issue by AXAET** [Polidea/RxAndroidBle#37]
When I write data to the device, the data is written to the success.But the Bluetooth device will automatically disconnect.The error that is displayed in Samsung S6 is "BleGattException{status=10, bleGattOperation=BleGattOperation{description='CHARACTERISTIC_WRITE'}}",but in other mobile phones, it is " BleGattException{status=133, bleGattOperation=BleGattOperation{description='CHARACTERISTIC_WRITE'}} ".I want to know how to solve it.I'm running an example.thanks

**Comment by dariuszseweryn** [comment]
Hello there.
Do you know to what device you're talking to? Do you know what characteristic you want to write?

Both of these statuses come from Android Bluetooth Stack and we cannot do much.
Status 133 is GATT_ERROR and status 10 is GATT_NOT_FOUND.

Perhaps you're trying to write a characteristic that is read only?
