### ISSUE TITLE
Issue Retrieving Already Connected Devices

### ISSUE THREAD

**Issue by logalleg** [Polidea/RxAndroidBle#375]
If a user manually connects to a Bluetooth device there is not a good way to get the already connected devices.

If you use ```getBondedDevices()``` that can return devices that are not connected, and if you use ```getBondedDevices()``` in conjunction with ```getConnectionState()``` this does not work because it reports that the device is not connected

**Comment by uKL** [comment]
I guess you're the one behind this StackOverflow question https://stackoverflow.com/questions/48888247/getting-already-connected-devices-from-rxandroidble

This seems to be a general usage question, so let's leave it on the stack.
