### ISSUE TITLE
Consider moving from a ConnectionSharingAdapter towards a ReplyingShare

### ISSUE THREAD

**Issue by uKL** [Polidea/RxAndroidBle#379]
Due to some issues with ConnectionSharingAdapter let's check if we can avoid it and use the ReplyingShare.

- [ ] Verify if replying share fits our needs
- [ ] Provide a migration paragraph in the readme

**Comment by RobLewis** [comment]
I use `ConnectionSharingAdapter`. What are its issues? And I think you may have a typo: isn't it `[ReplayingShare](https://github.com/JakeWharton/RxReplayingShare)`?

**Comment by streetsofboston** [comment]
We had some issues with the `ConnectionSharingAdapter` in a multithreaded environment. We wrote an updated version. This updated version would obtain/emit shared connections on one thread.

**Comment by RobLewis** [comment]
@streetsofboston I looked briefly at `ReplayingShare` and didn't notice any attention to threading. Do you think it would have the same issues as `ConnectionSharingAdapter`?

**Comment by streetsofboston** [comment]
The way `ReplayingShare` is working, is quite differently from the `ConnectionSharingAdapter`. I wouldn't be able to tell you if it had the same issues or not.

The way we fixed it was by `defer`-ing the `establishConnection` Observable and subscribing the deferred Observable on a Scheduler that is single-threaded.

**Comment by uKL** [comment]
We are going to deprecate `ConnectionSharingAdapter` and suggest usage of `ReplayingShare` in the future version.

**Comment by uKL** [comment]
Updated documentation on a `ReplyingShare`.

**Comment by RAM512** [comment]
Can you add ReplyingShare and firstOrError information to Readme.md please?
I'm new in ReactiveX and it's hard for me to understand use cases. For example in [example4_characteristic/CharacteristicOperationExampleActivity](https://github.com/Polidea/RxAndroidBle/blob/master/sample/src/main/java/com/polidea/rxandroidble2/sample/example4_characteristic/CharacteristicOperationExampleActivity.java) you use `.firstOrError()` in `onReadClick()` and `onWriteClick()` but not in `onNotifyClick()`.

**Comment by dariuszseweryn** [comment]
@RAM512 `.firstOrError()` is just a handy way to transform a `Observable<T>` to a `Single<T>`. For more information about `Observable` and/or `Single` I can encourage you to check for information directly on `RxJava`.

`ReplyingShare` is a helper (that should not be used imho) for using the same `RxBleConnection` in multiple places in the code while maintaining a single connection established (`RxBleDevice.establishConnection()` when unsubscribed closes the connection).

Best Regards
