### ISSUE TITLE
Possibility to specify the service as well as characteristic UUID for read, write and notify?

### ISSUE THREAD

**Issue by 6bangs** [Polidea/RxAndroidBle#38]
It's possible that a device can support multiple services that each expose a different characteristic with the same UUID; in the current API, there's no way to specify which service to use. This edge case shouldn't occur unless a device implements a custom profile, so it might make sense for the service UUID to be optional.

**Comment by dariuszseweryn** [comment]
In the next SNAPSHOT release there are added interface functions to use with raw Android `BluetoothGattCharacteristic` and `BluetoothGattDescriptor` which can be obtained from `RxBleDeviceServices` (`RxBleConnection.discoverServices()`)

**Comment by 6bangs** [comment]
That'll do it, thanks!
