### ISSUE TITLE
Unsubscribe notification

### ISSUE THREAD

**Issue by hgflas** [Polidea/RxAndroidBle#386]
Hello,

With the help of a button, the user can receive notifications of a characteristic. The following code will be executed:

`             connection.setupNotification(setDescriptorEnableNotification(tmpCharacterostoc, connection))
                    .flatMap(notificationObservable -> notificationObservable)
                    .observeOn(Schedulers.io())
                    .subscribeOn(Schedulers.io())
                    .subscribe(bytes -> {
                            //data processing
                    );
` 

If the user clicks on the button again, the notification should be unsubscribed, so that no notifications are received. 
How can i do this? I have try to set the value of the Descriptor to BluetoothGattDescriptor.DISABLE_NOTIFICATION_VALUE but it doesnt worked.

**Comment by uKL** [comment]
Hi, this is a general usage question. Please use StackOverflow with a tag #rxandroidble. The issue tracker is for bug and enhancements.
