### ISSUE TITLE
Gradle not finding RxJava2 version

### ISSUE THREAD

**Issue by RobLewis** [Polidea/RxAndroidBle#387]
I am using this line exactly as in the ReadMe: 
`compile "com.polidea.rxandroidble:rxandroidble2:1.5.0"`

Gradle says "Failed to resolve" it. 

(Parenthetically, I guess we're now supposed to replace `compile` with `api` or `implementation`)

**Comment by uKL** [comment]
Correct is `com.polidea.rxandroidble2:rxandroidble:1.5.0-SNAPSHOT`

Keep in mind that rxjava2 is not yet finished and we'll update the README soon, before the release ;)

**Comment by Rishvanth-Rishi** [comment]
though I used com.polidea.rxandroidble2:rxandroidble:1.5.0-SNAPSHOT still, I'm getting the same error(failed to resolve).

**Comment by dariuszseweryn** [comment]
Check readme for "snapshot"
