### ISSUE TITLE
Setting VERBOSE log level fixes disconnect errors(?)

### ISSUE THREAD

**Issue by RobLewis** [Polidea/RxAndroidBle#431]
Before filing an official issue, I wanted to ask: is it _remotely_ possible that the log level could have an effect on the reliability of `RxAndroidBle2`? 

```
        rxBleClient = RxBleClient.create(mContext);
        RxBleLog.setLogLevel(RxBleLog.VERBOSE);
        MainActivity.backgroundTimer.cancel();
        scanSubscriptionDisp = rxBleClient.scanBleDevices(
```

Without the log level setting, I'm getting random disconnections. With it, it seems to work OK. There are no other calls to `.setLogLevel()` in the app.

**Comment by dariuszseweryn** [comment]
No, it is not possible as for my level of understanding. I do not expect to see any timing issues after/before activating the log. Random disconnections may happen because of external (non-library) reasons.

Best Regards
