### ISSUE TITLE
Connection (almost) never established on Huawei P10 Lite (and other phones)

### ISSUE THREAD

**Issue by jensfrandsen** [Polidea/RxAndroidBle#440]
### Summary
Hi

We are updating our apps to use RxAndroidBLE. In general Bluetooth have become a lot smoother than the implementation that we had before with our own bluetooth implementation based on the standard Android library.
We have issues with the Huawei P10 Lite device (and probably others as well). The device quickly finds advertisements from the bluetooth device and a create connection request is made, however the connection is never established. I've seen it work a few rare times and then it usually worked a few times after each other.
Our old bluetooth implementation works well on the same device.
Our implementation using RxAndroidBle works well on f.x. our Pixel device and many older devices as well.
I know that this sounds like a device specific issue that doesn't belong here, but I'm reaching out in hope that anyone can help with this issue that is blocking us from releasing to our many users.
Mainly what I find weird is that our old implementation works well on this specific device (it then works worse on most other devices).
I got Bluetooth HCI Snoop Logs out of the device (see screenshots below) and where the old and RxAndroidBle version differs is that the bluetooth chipset of the Huawei P10 Lite never sends the LE Meta (LE CONNECTION COMPLETE) event back up to the stack. Up until and including the Create Connection Cmd is the same.

So I was thinking about whether some race condition or threading issue could be causing this, but since the link layer create connection command is the same, it is hard for me to imagine what it could be. I've tested this many many times, so it is not just some random coincidence.

### Library version
implementation 'com.polidea.rxandroidble2:rxandroidble:1.6.0'
implementation 'io.reactivex.rxjava2:rxandroid:2.0.2'

#### Preconditions
Running on Huawei P10 Lite

#### Logs from the application running with setting `RxBleLog.setLogLevel(RxBleLog.VERBOSE)`
HCI snoop log screenshots here:
Successful:
https://cl.ly/3w0L292J0b1P

Timeout
https://cl.ly/3K3o112z3T3Y

#### Actual result
Connection only establishes a few % of the tries

#### Expected result
That connection would be established

**Comment by dariuszseweryn** [comment]
Have you tried to stop the scan before establishing connection?

**Comment by jensfrandsen** [comment]
Looked through my code and realised that you are right. Scanning is not stopped before connecting. That is obviously a mistake.

Thank you!

**Comment by uKL** [comment]
That's not generally a mistake but some of Huawei's misbehave like that. I've experienced it before as well.
