### ISSUE TITLE
Comment on Wiki "FAQ: Cannot connect" item

### ISSUE THREAD

**Issue by RobLewis** [Polidea/RxAndroidBle#448]
There doesn't seem to be a way to comment directly on the [Wiki](https://github.com/Polidea/RxAndroidBle/wiki/FAQ:-Cannot-connect) so I'm noting this here: 
At least [one developer](https://github.com/prasanthmurugan) reported [here](https://github.com/googlesamples/android-BluetoothLeGatt/issues/44) that simply stopping scanning before connecting wasn't enough to connect successfully. Their solution was to insert a 500 ms delay after stopping the scan. (The linked item includes other things people have tried, some successfully. As is often the case it seems to be highly device-dependent.)

**Comment by uKL** [comment]
This is correct, in my case 250ms was enough for all devices that I had tested on. Worth noting, thanks!

**Comment by dariuszseweryn** [comment]
I have added a [`Connect right after scanning`](https://github.com/Polidea/RxAndroidBle/wiki/FAQ:-Cannot-connect#connect-right-after-scanning) paragraph
