### ISSUE TITLE
I tried to disconnect a device Bluetooth LE :/

### ISSUE THREAD

**Issue by Diviercadavid** [Polidea/RxAndroidBle#449]
### I tried to disconnect a device Bluetooth LE but no get success
I tried to disconnect a device but not find a way to do. can anybody help me?

**Comment by dariuszseweryn** [comment]
Hello!

Thank you for using the library.

This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rxandroidble) with `rxandroidble` tag—it will be easier to find by other users.

Best Regards

**Comment by kraghu** [comment]
It would been really useful if some of these questions were answered here instead of stackoverflow even if it is Rxjava issue. It'd avoid duplicates
