### ISSUE TITLE
I created a simple example of the use of RxBleCustomOperation

### ISSUE THREAD

**Issue by RobLewis** [Polidea/RxAndroidBle#450]
Recently I had a need to retrieve the Bluetooth GATT object from Android. Since `RxAndroidBle` doesn't offer this as a standard operation, I tried implementing it as a Custom Operation. 

For less-advanced programmers like me, `RxBleCustomOperation` isn't the easiest thing to understand. But I think I've got it, and I created [a Gist](https://gist.github.com/RobLewis/fc20bde8ce71c7da2040d04b2ba3c156) to explain how it works. Hope it may benefit someone else. You might consider adding it to the Wiki.

**Comment by Lloyd0577** [comment]
hello!,how to receive notify data by RxBleCustomOperation

**Comment by dariuszseweryn** [comment]
I have finally added [a Wiki page](https://github.com/Polidea/RxAndroidBle/wiki/RxBleCustomOperation) for this. Thank you @RobLewis !
