### ISSUE TITLE
Looks like Periodic RSSI example has some problem  

### ISSUE THREAD

**Issue by KrechkoMichael** [Polidea/RxAndroidBle#454]
this code from example5

> connectionSubscription = bleDevice.establishConnection(this, false)
                    .compose(bindUntilEvent(PAUSE))
                    .observeOn(AndroidSchedulers.mainThread())
                    .doOnUnsubscribe(this::clearSubscription)
                    .observeOn(Schedulers.io())
                    .flatMap(rxBleConnection -> // Set desired interval.
                            Observable.interval(2, SECONDS).flatMap(sequence -> rxBleConnection.readRssi()))
                    .subscribe(this::updateRssi, this::onConnectionFailure);

causes error 

> 11551-11669/com.polidea.rxandroidble.sample E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.polidea.rxandroidble.sample, PID: 11551
    io.reactivex.exceptions.UndeliverableException: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.

Code that doesn't cause error

> connectionSubscription = bleDevice.establishConnection(this, false)
                    .compose(bindUntilEvent(PAUSE))
                    .observeOn(AndroidSchedulers.mainThread())
                    .doOnUnsubscribe(this::clearSubscription)
                    .observeOn(Schedulers.io())
                    .flatMap(rxBleConnection -> // Set desired interval.
                            Observable.interval(2, SECONDS).flatMap(sequence -> rxBleConnection.readRssi()))
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(this::updateRssi, this::onConnectionFailure)

**Comment by dariuszseweryn** [comment]
Thanks for report!
