### ISSUE TITLE
ios connect much faster than android

### ISSUE THREAD

**Issue by dtingz** [Polidea/RxAndroidBle#455]
my ios teammate connecting to the device much faster than our android app..
for android it takes 6 sec
iphone 0.5 sec
how is it possible?

**Comment by dariuszseweryn** [comment]
Hello,

There may be a multitude of causes of this behaviour starting with availability of `Service Changed` characteristic, attributes caching, scan settings (time window, frequency of windows), chip used and so on.

The topic is very broad and not connected to the library itself therefore I am closing.

Best regards
