### ISSUE TITLE
On a project I am working on, I have 2 beacons but I want to connect to only one of them. the problem is after connecting to the first one the BLE scanner is still logging  advertisment packets from the  second one, is there a way to set a scan time out?

### ISSUE THREAD

**Issue by chenineazeddine** [Polidea/RxAndroidBle#457]
### Disclaimer
Before you will post a new issue to the RxAndroidBle library consider if you are filling a bug/feature request or a general question 
about:
* Usage of RxJava
* Usage of Bluetooth Low Energy
* Usage of RxAndroidBle
* Weird behaviour of the peripheral you are using
* Other not directly related to a new feature request or a bug

If any of the above points seems to match your use case — consider using Google or creating a question on www.stackoverflow.com with 
a tag `rxandroidble` where it will be easier to access by other people with similar questions. Issues that are not bugs or feature requests
will be closed.

### Library version
`X.X.X`

#### Steps to reproduce actual result
<br />1.
<br />2.
<br />3.

**Comment by dariuszseweryn** [comment]
Hello!

Thank you for using the library.

This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rxandroidble) with `rxandroidble` tag—it will be easier to find by other users.

Best Regards
