### ISSUE TITLE
RxBleConnection Observable is not emitting when called from a click event function

### ISSUE THREAD

**Issue by chenineazeddine** [Polidea/RxAndroidBle#461]
I am trying to write to a characteristic when a click happened, but the connection observable stop emitting few moments after the connection is established.

`fun setLampPowerState(state: LampProfile.State): Observable<LampProfile.State> {
        Log.d(TAG,"Go for it ")
        return lampBleConnection.subscribeOn(Schedulers.from(bluetoothExecutor))
                .observeOn(AndroidSchedulers.mainThread())
                .flatMap {
                    Log.d(TAG,"writing to the Characteristic")
                    it.writeCharacteristic(UUID.fromString(LampProfile.STATE_CHARACTERISTIC_UUID), byteArrayOf(state.value.toByte()))
                            .toObservable()}
                .map {
                    it[0].toInt() }
                .flatMap {
                    Log.d(TAG,"Finish writing")
                    when (it) {
                        0 -> Observable.just(LampProfile.State.OFF)
                        1 ->  Observable.just(LampProfile.State.ON)
                        else -> Observable.error(Throwable("unknown value")) }}
    }``

**Comment by dariuszseweryn** [comment]
Hello!

Thank you for using the library.

This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rxandroidble) with `rxandroidble` tag—it will be easier to find by other users.

Best Regards
