### ISSUE TITLE
Fail to connect

### ISSUE THREAD

**Issue by sh4wn** [Polidea/RxAndroidBle#467]
I have fail to connect to my ble device with my xiaomi 5s plus.
I believe this is what happen:
https://medium.com/@steffandroid/i-would-actually-advise-against-this-d37e5bccaff5

### Library version
`1.5.0`

**Comment by dariuszseweryn** [comment]
Hello,

Thank you for using the library.
Your post seems to be a bug report but it lacks some crucial information. Could you edit to contain information according to the [issue template](https://github.com/Polidea/RxAndroidBle/blob/master/.github/ISSUE_TEMPLATE.md)?

Best Regards

**Comment by dariuszseweryn** [comment]
Closing due to lack of information and inactivity of the original poster.

When more data will be available—feel free to add that information and reopen this issue.

Best Regards
