### ISSUE TITLE
Should RxAndroidBle integrate Android-Scanner-Compat-Library?

### ISSUE THREAD

**Issue by ened** [Polidea/RxAndroidBle#469]
**Library version**: `1.7.0`

This is more of a feature suggestion & idea to reduce work, feel free to close if the project has already decided on it.

There are now various Android SDK levels & BLE APIs, which is hard to change due to device distribution and will only be solved in the years to come.
However, I see little need for multiple open source projects to basically write the same code (and maybe bugs) rgd. BLE scanning, reading/writing etc. 

For example, this project is dedicated to BLE scanning: https://github.com/NordicSemiconductor/Android-Scanner-Compat-Library

They have already catched up to API 26 (rgd. the `isConnectable` flag in `ScanRecord`), so RxAndroidBle would require a PR to add essentially the same code, as well.

Is it worth a consideration to drop all scanning code from this project and use this dependency, instead? You only need to write a Rx wrapper and done.

**Comment by dariuszseweryn** [comment]
Hello,

Thanks for the suggestion. We were already evaluating the idea quite a long time ago and decided to reduce dependencies on outside libraries as we couldn't contact the original developers.

Best Regards
