### ISSUE TITLE
readRssi() may put the phone in a weird state

### ISSUE THREAD

**Issue by GuillaumeBo** [Polidea/RxAndroidBle#470]
I am using rxAndroidBle1.7with rx2

I have to inform my BLE device about the RSSI during the connection. So the only way to do it is to call the gatt function "readRemoteRssi" that are implemented in the RX lib with the name "readRssi".

This function works well in the basic case, call at anytime with nothing arround.

In my usecase my BLE Device informs me to give it the rssi value. So i am registered to a notification and when i receive a notif, i read rssi value and send it with a writeCharacteristic.
But at the first try to read rssi value inside a notif event, the readRssi method return nothing, and the smartphone will never return anymore any RSSI value (even with the simple basic impletation of the GATT). After strong inspection on ble device side, the smartphone sends nothing or rssi request after that.

The only solution to make it work again is to reset networks settings on the phone.... After that it's works again on basic case and if i retry with notif response we go back in the broken mode...

So i am thinking about thread history, but even a reboot of the phone or on/off BLE do not cure this issue. I have no more track to solve this.. I try i think every possibilities for onSubscribe and onObserve..

```
connection.setupNotification(UUID.fromString("xxxxxx")).subscribe(observable -> {
            observable.subscribe(bytes -> {
                    connection.readRssi().subscribe(integer -> {
                    Log.e(TAG, "RSSI = " + integer);
                }, throwable -> {
                    Log.e(TAG, "RSSI fail");
                });
            }, throwable -> {

            });
        }, throwable -> {
        });
```
So if anyone has an idea?

**Comment by dariuszseweryn** [comment]
In this case I am closing the issue. 

FYI I could not see what was happening because there are no logs in the original post (as asked by the issue template).
