### ISSUE TITLE
Is possible to subscribe to multiple characteristic notifications at once?

### ISSUE THREAD

**Issue by vlmax74** [Polidea/RxAndroidBle#473]
How does the code describe in https://github.com/Polidea/RxAndroidBle/issues/61 must be changed to  be ported in RxAndroidBle2 version (v 1.7)?

This code works perfectly on 1.4.1 but not in 1.7

```
    final UUID serviceUuid = // your service UUID
    final Map<UUID, byte[]> genericModel = new HashMap<>();
    final Observable<RxBleConnection> connectionObservable = // your connectionObservable

    connectionObservable
            .flatMap(connection -> 
                    connection.discoverServices()
                            .flatMap(services -> services.getService(serviceUuid).map(BluetoothGattService::getCharacteristics)) // get characteristics you're interested in
                            .flatMap(Observable::from) // deal with every characteristic separately
                            .flatMap(characteristic -> connection
                                            .setupNotification(characteristic) // setup notification for each
                                            .flatMap(observable -> observable), // to get the raw bytes from notification
                                    Pair::new) // merge characteristic with byte[] to keep track from which characteristic the bytes came
            )
            .subscribe(
                    pair -> genericModel.put(pair.first.getUuid(), pair.second),
                    throwable -> { /* handle errors */}
            ); 
```

**Comment by RobLewis** [comment]
I haven't delved deeply into this, but one problem could be that in v.2, `discoverServices()` returns a `Single` instead of an `Observable`, and the `flatMap()` operator for `Single` also returns a `Single`. You may need to use `flatMapObservable()` or some other function. HTH.

**Comment by dariuszseweryn** [comment]
What do you mean by:
> This code works perfectly on 1.4.1 but not in 1.7

If it does not compile then the types do not match. The compiler will inform you specifically what is not correct. In this situation you should look into `.flatMapObservable()` or `.flatMapCompletable()` functions and put them in appropriate places where `.flatMap()` is currently used.
