### ISSUE TITLE
Fatal Bug: IllegalArgumentException in UUIDUtil

### ISSUE THREAD

**Issue by ecexplorer** [Polidea/RxAndroidBle#482]
### Summary
Active BLE scan over a long period of time (4+ minutes), right after another device is discovered, I get a fatal exception "java.lang.IllegalArgumentException: Bad position 96/62"

The full stack trace follows:
```
09-18 10:10:29.973 14580 14580 E AndroidRuntime: FATAL EXCEPTION: main
09-18 10:10:29.973 14580 14580 E AndroidRuntime: java.lang.IllegalArgumentException: Bad position 96/62
09-18 10:10:29.973 14580 14580 E AndroidRuntime: 	at java.nio.Buffer.position(Buffer.java:249)
09-18 10:10:29.973 14580 14580 E AndroidRuntime: 	at com.polidea.rxandroidble.internal.util.UUIDUtil.extractUUIDs(UUIDUtil.java:100)
09-18 10:10:29.973 14580 14580 E AndroidRuntime: 	at com.polidea.rxandroidble.internal.operations.LegacyScanOperation$1.onLeScan(LegacyScanOperation.java:39)
09-18 10:10:29.973 14580 14580 E AndroidRuntime: 	at android.bluetooth.BluetoothAdapter$2.onScanResult(BluetoothAdapter.java:2468)
09-18 10:10:29.973 14580 14580 E AndroidRuntime: 	at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:477)
09-18 10:10:29.973 14580 14580 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
09-18 10:10:29.973 14580 14580 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
09-18 10:10:29.973 14580 14580 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
09-18 10:10:29.973 14580 14580 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6592)
09-18 10:10:29.973 14580 14580 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-18 10:10:29.973 14580 14580 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
09-18 10:10:29.973 14580 14580 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
```

From the best I can tell, the extractUUIDs method in UUIDutil can get in a state where the buffer position is off, and without a try/catch guard against the bad position request, the exception is thrown. Apologies in advance for not knowing the specifics of how extractUUIDs works and why the buffer position would be off. Happy to provide more diagnostic information if helpful, as I'm able to reproduce with some frequency.

### Library version
RxAndroidBle 1.6.0
used in
react-native-ble-plx 0.10.0

#### Preconditions
Device exhibiting error: Moto X4, Android 8.0

#### Steps to reproduce actual result
<br />1. Start BLE scan (startDeviceScan) in presence of many devices. allowDuplicates is set to true
<br />2. Continue scanning over long period of time
<br />3. Wait for crash

**Comment by dariuszseweryn** [comment]
Fixed in `1.7.0 RxJava1` release which should be used on the next `react-native-ble-plx@1.0.0` release.
