### ISSUE TITLE
How to get major and minor number of a bluetooth beacon

### ISSUE THREAD

**Issue by brad007** [Polidea/RxAndroidBle#489]
Does anyone know how to get the major and minor number of a bluetooth beacon

**Comment by dariuszseweryn** [comment]
Hello!

Thank you for using the library.

This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rxandroidble) with `rxandroidble` tag—it will be easier to find by other users. Also feel free to check already posted questions as a similar one may be already answered.

Best Regards
