### ISSUE TITLE
Migrate library to use androidx dependencies

### ISSUE THREAD

**Issue by RobLewis** [Polidea/RxAndroidBle#494]
I'm just beginning to look into androidx. Evidently there is some work involved in migrating a library like RxAndroidBle to it, but I have no idea how much. 

Can you comment on the status of this? Any idea of timing?

**Comment by RobLewis** [comment]
TBH I don't know enough about androidx to answer. My understanding is that most of the job consists of renaming packages, but I'm not sure. I just noticed that the [work has apparently started](https://github.com/JakeWharton/RxBinding/issues/460) on migrating Jake Wharton's RxBinding.

**Comment by dariuszseweryn** [comment]
`1.8.0-SNAPSHOT` is already using AndroidX dependencies. Thanks!
