### ISSUE TITLE
How to setWriteType for a characteristic

### ISSUE THREAD

**Issue by mohsenoid** [Polidea/RxAndroidBle#495]
Hi, after greeting and appreciation for your nice job,

My question is, our BLE peripheral writable characteristic supports `PROPERTY_WRITE` plus `PROPERTY_WRITE_NO_RESPONSE`, and on App side when I call `bleConnection.writeCharacteristic` it only works with no response cause I get `onSuccesss` so fast even when something is wrong on the device side.

Based on Android BLE API doc it is possible to set how to write:
https://developer.android.com/reference/android/bluetooth/BluetoothGattCharacteristic.html#setWriteType(int)

and I noticed if I want to set it using the library I have to use `getCharacteristic(uuid)` method which has been already deprecated from your side!

is there any solution to set write with a response when Characteristic support both?

**Comment by dariuszseweryn** [comment]
Hello

You may use `RxBleConnection.discoverServices()` and then search the `RxBleDeviceServices` for the `BluetoothGattCharacteristic` you are interested in. Then you can set the `BluetoothGattCharacteristic.setWriteType(int)` method and start to use `RxBleConnection.writeCharacteristic(BluetoothGattCharacteristic, byte[])`.

Best Regards

**Comment by dariuszseweryn** [comment]
Since the OP has reacted to the answer I assume thing is sorted out. Closing

If mistaken feel free to add more info or reopen.

**Comment by hjh2881** [comment]
can you share the basic code ?i don't know how to send data with write type no_response
