### ISSUE TITLE
Possible concurrency issue

### ISSUE THREAD

**Issue by artem-zinnatullin** [Polidea/RxAndroidBle#5]
Yo guys, was just looking into sources and found pretty [suspicious usage of non-thread-safe collection](https://github.com/Polidea/RxAndroidBle/blob/7e694dad75756fa1664d89409e0adc3fa3c1ecf5/rxandroidble/src/main/java/com/polidea/rxandroidble/RxBleClientImpl.java#L34).

Please consider using `ConcurrentHashMap` there because it may be accessed from different threads with `subscribeOn` and `unsubscribeOn`.

Library looks nice! (extra points for Spock!)

**Comment by uKL** [comment]
Yes, this may be true, we will take a look. However ConcurrentHashMap may not be enough. We should synchronize whole read/create operation.

**Comment by uKL** [comment]
Issue will be fixed by https://github.com/Polidea/RxAndroidBle/pull/6.
