### ISSUE TITLE
check out from version control doesn't have GitHub

### ISSUE THREAD

**Issue by Rogue899** [Polidea/RxAndroidBle#500]
![2018-10-24 1](https://user-images.githubusercontent.com/16031742/47425761-055e5500-d794-11e8-815c-6200f92ef72c.png)
![2018-10-24](https://user-images.githubusercontent.com/16031742/47425762-05f6eb80-d794-11e8-95d6-e69820c7da27.png)

Before I used to have GitHub and Git but now after deleting android studio and reinstalling it, it seems that I can't find GitHub

**Comment by dariuszseweryn** [comment]
Hello,

I do not see how this is a library issue

**Comment by Rogue899** [comment]
> Hello,
> 
> I do not see how this is a library issue

i do not know what is the issue but after googling the problem many people suggested that maybe it is a plugin issue so i screenshot it for clarification, the question is why isn't github showing in the VCS...

**Comment by dariuszseweryn** [comment]
I think that you should ask this question to the authors of `Android Studio` this is a project site of Android Bluetooth Low Energy library and we are not developing `Android Studio`.

There was however [an issue with checking out the library and building it later](https://github.com/Polidea/RxAndroidBle/issues/500) but it is also an issue in `Android Studio` itself.

Anyway I cannot help you with the lack of `Github` option when trying to checkout code in `Android Studio`.

You probably can simply use `Git` option as `Github` is using `Git`

Best Regards
