### ISSUE TITLE
establishConnection sometimes doesn't return after bluetooth has been turned on on the device

### ISSUE THREAD

**Issue by micHar** [Polidea/RxAndroidBle#516]
### Summary

When I turn off BT and then turn it on again, sometimes (non-deterministically) the subsequent calls to `RxBleDevice.establishConnection` stop sending `onNexts` forever (of course I use `retry()` there).

### Library version
`1.7.1`

#### Minimum code snippet reproducing the issue

    bleClient.getBleDevice(macAddress)
            .establishConnection(false)
            .doOnError { Log.v("aaa", "Error: $it") }
            .doOnNext { Log.v("aaa", "Connected") }
            .map<Connection> { StableConnection }
            .startWith(Connecting)
            .doOnNext { Log.v("aaa", "$it") }
            .retryWhen { it.delay(2, SECONDS) }

#### Actual result

After switching the BT in the system a few times, I get just the `Connecting` status every time - no `StableConnection`. When I switch it off, the `com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from __:__:__:__:__:__ with status -1 (UNKNOWN)` is logged every time. But it never recovers to show the `StableConnection` status again (in other words `aaa: Connected` never shows in the logs). This never happens when I switch the bluetooth device off, just with the bluetooth switch in android system.

#### Expected result

After switching BT on, it should show `Connecting` and then `StableConnection`

**Comment by dariuszseweryn** [comment]
Hello,

Thanks for using the library! Could you provide logs showing the issue?

Best Regards

**Comment by micHar** [comment]
Sure! Just please don't close the issue too fast, because I may not find time for that in the upcoming holidays, I'll try to do it asap.

**Comment by dariuszseweryn** [comment]
I see one mismatch between the logs and the code snippet you have posted:
- There is no 2 seconds delay between retries

This may point to a different bug in the application code — the downstream is disposing right after subscribing to `.establishConnection()` and retrying immediately in a cycle.

`Disconnect operation has been executed but GATT instance was null - considering disconnected.` will allways be logged whenever `ConnectOperation` will not be subscribed long enough to get a reference to `BluetoothGatt`.

**Comment by micHar** [comment]
I've changed it since to 200ms, it was easier to reproduce, but earlier I could reproduce it with 7 seconds retry, too.

My snippet could be too simple, it also contains the `replayingShare()` at the end and generally there are several clients of this observable and they do connect and disconnect at different moments (mostly because of application's lifecycle).

> the downstream is disposing right after subscribing to .establishConnection()

I'm not sure about the specifics of replaying share, but if there was a moment where no observer was subscribed to this observable, it caused this behaviour?

Also I'm pretty sure that in the last test I just left it for some time on a screen so it was subscribed all the time and at some points it just stopped working. Cannot reproduce it with 2s now, but will try different intervals.

**Comment by micHar** [comment]
To rephrase the original code sample - this is enough to see the error on my device (Samsung Galaxy S8, will try something else too):

```
1. disable the bluetoooth in the system
2. Run the following code.
3. Wait around 100 retries.

bleClient
            .getBleDevice("F9:56:A3:67:AC:F0")
            .establishConnection(false)
            .retryWhen { it.delay(200, MILLISECONDS) }
            .subscribe()
```

**Comment by dariuszseweryn** [comment]
Could you add a log of the exception in `.retryWhen { it.delay(200, MILLISECONDS) }`?
Something like `.retryWhen { it.doOnNext(throwable -> Log.e("whoopsey", "bummer", throwable)).delay(200, MILLISECONDS) }` and show the logs?

**Comment by micHar** [comment]
Sure, but I didn't find anything interesting there, that's why I omitted them: https://gist.github.com/micHar/2faee160c431d89b0e60c34a8c26d4e2
 (the retry #19 breaks).

Also, I noticed that when I `subscribeOn(Schedulers.io())` it takes a lot more retries to break so this may be some threading issue.

**Comment by dariuszseweryn** [comment]
I am a bit confused — could you describe the reproduction steps as in the issue template?

**Comment by micHar** [comment]
OK, I have more details now, so it's probably a good idea.

### Summary

### Library version
`1.7.1`

#### Preconditions

None.

#### Steps to reproduce actual result
<br />1. Disable bluetooth in system (e.g. from system tray).
<br />2. Run the app which runs the code below.
<br />3. Wait for some times, it occurs after ~100 retries usually

#### Minimum code snippet reproducing the issue
```
bleClient.getBleDevice(macAddress)
            .establishConnection(false)
            .retryWhen { it.delay(200, MILLISECONDS) }
            .subscribe()
```

#### Logs from the application running with setting `RxBleLog.setLogLevel(RxBleLog.DEBUG)`

```
2018-12-23 13:32:06.087 D/RxBle#DisconnectionRouter: DisconnectionRouter
2018-12-23 13:32:06.098 I/RxBle#ConnectionOperationQueue: Connection operations queue to be terminated (F9:56:A3:67:AC:F0)
2018-12-23 13:32:06.099 D/RxBle#Executors$RunnableAdapter: Terminated.
2018-12-23 13:32:06.101 D/RxBle#ClientOperationQueue: QUEUED   ConnectOperation(57844933)
2018-12-23 13:32:06.102 V/RxBle#retriesCounter: Retry #149
2018-12-23 13:32:06.105 D/RxBle#ClientOperationQueue: STARTED  ConnectOperation(57844933)
2018-12-23 13:32:06.106 D/RxBle#ClientOperationQueue: QUEUED   DisconnectOperation(190995994)
2018-12-23 13:32:06.106 D/RxBle#ClientOperationQueue: The operation was about to be run but the observer had been already disposed: com.polidea.rxandroidble2.internal.operations.ConnectOperation@372a4c5
2018-12-23 13:32:06.108 D/RxBle#ClientOperationQueue: FINISHED ConnectOperation(57844933) in 4 ms
2018-12-23 13:32:06.110 D/RxBle#ClientOperationQueue: STARTED  DisconnectOperation(190995994)
2018-12-23 13:32:06.112 W/RxBle#QueueOperation: Disconnect operation has been executed but GATT instance was null - considering disconnected.
2018-12-23 13:32:06.114 D/RxBle#ClientOperationQueue: FINISHED DisconnectOperation(190995994) in 5 ms
2018-12-23 13:32:06.312 D/RxBle#DisconnectionRouter: DisconnectionRouter
2018-12-23 13:32:06.319 I/RxBle#ConnectionOperationQueue: Connection operations queue to be terminated (F9:56:A3:67:AC:F0)
2018-12-23 13:32:06.322 D/RxBle#Executors$RunnableAdapter: Terminated.
2018-12-23 13:32:06.322 D/RxBle#ClientOperationQueue: QUEUED   ConnectOperation(87572966)
2018-12-23 13:32:06.324 D/RxBle#ClientOperationQueue: STARTED  ConnectOperation(87572966)
2018-12-23 13:32:06.326 V/RxBle#retriesCounter: Retry #150
2018-12-23 13:32:06.329 D/RxBle#ClientOperationQueue: QUEUED   DisconnectOperation(183259943)
```

#### Actual result

After ~100 retries (in the above example it's retried at 13:32:06.312), the app stops properly retrying the connection to the BleDevice. When it fails once, it never recovers. There are two visible changes when it fails:

1.  The logs change, i.e. both `Connect operation` and `Disconnect operation` are NOT `STARTED` and `FINISHED` anymore (according to logs).
2. When I enable Bluetooth in that state, it never again connects to the device, i.e. `bleClient.getBleDevice(macAddress).establishConnection(false)` never emits onNext.

#### Expected result

Regardless of number of retries during the time when Bluetooth is disabled, when I enable it, the `bleClient.getBleDevice(macAddress).establishConnection(false)` should connect again.

**Comment by dariuszseweryn** [comment]
I have just made release `1.7.2` — it should have this issue fixed

**Comment by micHar** [comment]
Great news! Will check soon. Thanks for that, your support here is exceptional.

**Comment by micHar** [comment]
I have just checked and it works perfect, thank you!
