### ISSUE TITLE
State.BLUETOOTH_NOT_ENABLED in observeStateChanges is called twice

### ISSUE THREAD

**Issue by akhbulatov** [Polidea/RxAndroidBle#525]
Hi. I have a problem with the fact that `State.BLUETOOTH_NOT_ENABLED` in `observeStateChanges` is called twice. After the first call I connect Bluetooth via Intent, and after connecting, this state is called again first, and then `State.LOCATION_SERVICES_NOT_ENABLED`. Perhaps this behavior is not related to the library, but to my lack of knowledge of RxJava, but I would like to know the answer. Here is the sample:
```
override fun observeStateChanges(): Observable<BleState> =
        rxBleClient.observeStateChanges()
            .startWith(rxBleClient.state)
            .switchMap { state ->
                when (state) {
                    RxBleClient.State.READY -> {
                        Timber.d("Bluetooth state is ready.")
                        Observable.just(BleState.READY)
                    }
                    RxBleClient.State.BLUETOOTH_NOT_AVAILABLE -> {
                        Timber.e("Bluetooth not available.")
                        Observable.just(BleState.BLUETOOTH_NOT_AVAILABLE)
                    }
                    RxBleClient.State.BLUETOOTH_NOT_ENABLED -> {
                        Timber.e("Bluetooth not enabled.")
                        Observable.just(BleState.BLUETOOTH_NOT_ENABLED)
                    }
                    RxBleClient.State.LOCATION_PERMISSION_NOT_GRANTED -> {
                        Timber.e("Location permission not granted.")
                        Observable.just(BleState.LOCATION_PERMISSION_NOT_GRANTED)
                    }
                    RxBleClient.State.LOCATION_SERVICES_NOT_ENABLED -> {
                        Timber.e("Location services not enabled.")
                        Observable.just(BleState.LOCATION_SERVICES_NOT_ENABLED)
                    }
                    else -> {
                        Timber.e("Unknown bluetooth state.")
                        Observable.just(BleState.UNKNOWN)
                    }
                }
            }
```
And here is the log:
```
19:37:22 observeStateChanges: Bluetooth not enabled.
19:37:29 observeStateChanges: Bluetooth not enabled.
19:37:30 observeStateChanges: Location services not enabled.
19:37:35 observeStateChanges: Bluetooth state is ready.
```

**Comment by dariuszseweryn** [comment]
This is an implementation detail of the library. When the user turns the BT adapter ON the predicted adapter changes are `BluetoothAdapter.STATE_OFF -> BluetoothAdapter.STATE_TURNING_ON` and `BluetoothAdapter.STATE_TURNING_ON -> BluetoothAdapter.STATE_ON`.

Currently `rxBleClient.observeStateChanges()` does not track the state at the subscription time and only relays changes. The first change is `BluetoothAdapter.STATE_OFF -> BluetoothAdapter.STATE_TURNING_ON` which translates to `RxBleClient.State.BLUETOOTH_NOT_ENABLED` (it is the same for `BluetoothAdapter.STATE_OFF` and `BluetoothAdapter.STATE_TURNING_OFF` as well)

If that is an issue for you — you can quickly workaround by using:
```
        rxBleClient.observeStateChanges()
            .startWith(rxBleClient.state)
            .distinctUntilChanged()
```

**Comment by akhbulatov** [comment]
Okay, thanks for the answer)
