### ISSUE TITLE
How to request establishing connection for more than one device at one time

### ISSUE THREAD

**Issue by zetokz** [Polidea/RxAndroidBle#526]
General question about:
* Usage of RxAndroidBle

### Summary
Let say I have 10 Bluetooth devices to be connected in my app. My connection timeout is 30 sec (default one), so if 9 of my devices will be out of range my app is waiting 4 minutes 30 sec in the worst case in order to connect to this device that is in phone range. And this time for waiting will be only increasing with a count of devices in the account because I do not know which one is in phone range at this time. 
Definitely, I can decrease connection timeout but it does not sound like a solution because in worth case app will be waiting for (N - count of devices in account) `(N - 1) * timeout`.
Another solution can be creation several instances of RxBleClient that is not recommended but I saw people were using this for some cases.
And the best (for my opinion) can be running scan before calling connect to see which devices are in range and connect to them first.
Can you suggest anything else, how can I decrease the time of waiting for connection if I have many devices in the account?

### Library version
`1.6.0`

Thank you for any help!

**Comment by dariuszseweryn** [comment]
Hello!

Thank you for using the library.

This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rxandroidble) with `rxandroidble` tag—it will be easier to find by other users. Also feel free to check already posted questions as a similar one may be already answered.

Best Regards
