### ISSUE TITLE
Possibility to disable Toast messages coming from RxAndroidBle

### ISSUE THREAD

**Issue by hyyu** [Polidea/RxAndroidBle#545]
Hi,

Is there any mean to remove the toast when the connection is interrupted? I would like to have my own error handling, as I have my own styled components to fit my App Theme.

Version: 1.7.1

Behaviour:

When the connection is interrupted, a Toast appears to inform the connection couldn't be established
Screenshot:

<img src="https://user-images.githubusercontent.com/13220072/52631140-45218780-2ebe-11e9-8d88-f0a4aa4f2383.png" width="300" height="600">

Is there any way to remove the toast from my side, so I can replace it?

**Comment by dariuszseweryn** [comment]
I am afraid that what you are referencing has no connection to the library. You should ask the app developer.

Best Regards

**Comment by jreehuis** [comment]
I already experienced the same issue. It is not connected to the library itself.
Some smartphone vendors include this toasts upon BT errors.
I think they can not be avoided without switching the phone/vendor.

**Comment by hyyu** [comment]
Thanks for the answers, it seems that it's like jreehuis told, coming from the phone itself.

**Comment by dariuszseweryn** [comment]
What phone / OS version you experience those toasts with? I have not seen them at all

**Comment by hyyu** [comment]
I've had it on Google phones. My personnal phone is a Pixel 3 XL, and had it on Nexus phones.

**Comment by jreehuis** [comment]
E.g. on a Huawei P10, Android 8 or some Samsung Phones but I can not recall which ones. I also have in mind to have them seen on Sony devices aswell.
It is already some time ago when I had a closer look. By mind the toast came up in the case that the phone has still a BT bonding but the device has lost or invalidated the bonding key.

**Comment by dariuszseweryn** [comment]
Is the app you provided a screenshot from open sourced? If so could you add a link?

**Comment by hyyu** [comment]
It's an app I'm currently developing, it is associated to a connected Ble device.
