### ISSUE TITLE
Why Operations are removed from the Queue ?

### ISSUE THREAD

**Issue by LeMimit** [Polidea/RxAndroidBle#548]
### Summary

Hello !

First, I would like to say that I love this library and the work around it. Thanks for it 👍 

I would like yo understand the functioning of the library concerning the Queue of Operation.
I have seen "REMOVED" logs when I am doing operation. Can you explain to me, what are the condition s for a Operation to be removed from the Queue ?

Fot the needs of my project, I have to send a first array which is less than 20 bytes and then send a long array with a BatchSize of 20 bytes. I am writing in the same Characteristic.
It is possible that this code is called twice in a short time.

One of my operation is removed from the Queue and not performed.
I would like to understand why this operation is removed and then find a solution to make it work !

Thanks a lot.

### Library version
`1.7.1`

#### Minimum code snippet reproducing the issue
```Java
Observable.fromArray(ArrayToSend)
                .flatMapSingle(bytes -> connection.writeCharacteristic(writeCharacteristic, bytes))
                .flatMap(bytes -> connection.createNewLongWriteBuilder()
                        .setBytes(LongArrayToSend)
                        .setCharacteristic(writeCharacteristic)
                        .setMaxBatchSize(20)
                        .build()
```

#### Logs from the application running with setting `RxBleLog.setLogLevel(RxBleLog.VERBOSE)`
```
02-20 10:36:59.228 12631-13266 D/RxBle#ConnectionOperationQueue: QUEUED   CharacteristicWriteOperation(5368428)
02-20 10:36:59.229 12631-13209 D/RxBle#ConnectionOperationQueue: STARTED  CharacteristicWriteOperation(5368428)
02-20 10:36:59.230 12631-13266 D/RxBle#ConnectionOperationQueue: QUEUED   CharacteristicWriteOperation(265434683)
02-20 10:36:59.233 12631-12645 D/RxBle#BluetoothGatt: onCharacteristicWrite characteristic=a0000602-0451-4000-b000-000000000001 status=0
02-20 10:36:59.235 12631-13210 D/RxBle#ConnectionOperationQueue: QUEUED   CharacteristicLongWriteOperation(218747569)
02-20 10:36:59.235 12631-13209 D/RxBle#ConnectionOperationQueue: FINISHED CharacteristicWriteOperation(5368428) in 6 ms
02-20 10:36:59.236 12631-13209 D/RxBle#ConnectionOperationQueue: STARTED  CharacteristicWriteOperation(265434683)
02-20 10:36:59.239 12631-12646 D/RxBle#BluetoothGatt: onCharacteristicWrite characteristic=a0000602-0451-4000-b000-000000000001 status=0
02-20 10:36:59.241 12631-13210 D/RxBle#ConnectionOperationQueue: QUEUED   CharacteristicLongWriteOperation(21418902)
02-20 10:36:59.242 12631-13209 D/RxBle#ConnectionOperationQueue: FINISHED CharacteristicWriteOperation(265434683) in 5 ms
02-20 10:36:59.243 12631-13209 D/RxBle#ConnectionOperationQueue: STARTED  CharacteristicLongWriteOperation(218747569)
02-20 10:36:59.244 12631-12806 D/RxBle#CharacteristicLongWriteOperation: Writing next batch
02-20 10:36:59.246 12631-12698 D/RxBle#BluetoothGatt: onCharacteristicWrite characteristic=a0000602-0451-4000-b000-000000000001 status=0
02-20 10:36:59.248 12631-13210 D/RxBle#ConnectionOperationQueue$2: REMOVED  CharacteristicLongWriteOperation(21418902)
02-20 10:36:59.249 12631-13209 D/RxBle#ConnectionOperationQueue: FINISHED CharacteristicLongWriteOperation(218747569) in 6 ms
```

**Comment by dariuszseweryn** [comment]
Hello!

Thank you for using the library.

This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rxandroidble) with `rxandroidble` tag—it will be easier to find by other users. Also feel free to check already posted questions as a similar one may be already answered.

Generally your code snippet does not show it but the code is disposing the `CharacteristicLongWriteOperation` before it is even started — this is why it gets removed.

Best Regards

P.S. I really admire the fact that you have conformed to the issue template 💪 🚀
