### ISSUE TITLE
Allow monitoring RxBleClient state with observable. 

### ISSUE THREAD

**Issue by Cierpliwy** [Polidea/RxAndroidBle#55]
### Summary

Currently there is no API to monitor BLE state with observables. [On iOS](https://developer.apple.com/library/mac/documentation/CoreBluetooth/Reference/CBCentralManager_Class/index.html#//apple_ref/c/tdef/CBCentralManagerState) there is a property which allows you to know if BLE was turned off, is unsupported etc. It would be nice to have an observable emitting such state changes which could be then chained with other functions (for example scanning).

It's a feature request.

**Comment by dariuszseweryn** [comment]
Your Patience has been rewarded. `1.3.0-SNAPSHOT` now - `1.3.0` soon™.
