### ISSUE TITLE
Regarding the connection of multiple ble devices (5), does it affect the performance of the Notify devices and how to operate and call the Notify devices?

### ISSUE THREAD

**Issue by mfxscott** [Polidea/RxAndroidBle#550]
We have a new requirement, we need to connect several (5-20) ble devices with pad, and listen to the data returned by different ble device sensors at the same time for analysis. Could you please tell us how to use your library for development.Thanks

**Comment by dariuszseweryn** [comment]
Hello!

Thank you for using the library.

This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rxandroidble) with `rxandroidble` tag—it will be easier to find by other users. Also feel free to check already posted questions as a similar one may be already answered.

Best Regards
