### ISSUE TITLE
BleCharacteristicNotFoundException: Characteristic not found with UUID

### ISSUE THREAD

**Issue by SeloSlav** [Polidea/RxAndroidBle#559]
I am unable to retrieve data from my device despite supplying what I believe to be the correct UUID: ``D/ERROR:: com.polidea.rxandroidble2.exceptions.BleCharacteristicNotFoundException: Characteristic not found with UUID 00001101-0000-1000-8000-00805f9b34fb``. What should I do instead?

```
// Get device from scan
rxBleDevice = scanResult.bleDevice

val deviceUUID = UUID.fromString(scanResult.bleDevice.bluetoothDevice.uuids[0].toString())

// Check device info
println("Name: " + scanResult.bleDevice.name) // Prints to "TestDevice"
println("MAC Address: " + scanResult.bleDevice.macAddress) // Prints to "34:81:F4:3C:2D:7B"
println("UUID = $deviceUUID") // Prints to "00001101-0000-1000-8000-00805f9b34fb"
println("Service UUIDs = " + scanResult.scanRecord.serviceUuids) // Prints to "null"

/* Establish connection to device */
rxBleDevice!!.establishConnection(false) ?
 .doOnNext {
  _ ->
   Log.d("Device: ", "Connection Established")
 } ?
 .flatMapSingle {
  rxBleConnection ->
   deviceUUID? .let {
    rxBleConnection.readCharacteristic(it)
   }
 } ? .subscribe({
  count ->
  // count should be in bytes
  println("SUCCESS: $count")

 }, {
  throwable ->
  Log.d("ERROR: ", "$throwable")
 })
```

My expected output is a byte array that reads "datc00099", for example.

**Comment by jreehuis** [comment]
You are trying to read from a characteristic but giving a service UUID. As usually the characteristic and service UUIDs are different so I guess you have to find the right characteristic UUID.
Which UUID you have to use depends on the BT Device and Firmware Implementation you are using.

**Comment by SeloSlav** [comment]
Which one is the service UUID?

This one?

val deviceUUID = UUID.fromString(scanResult.bleDevice.bluetoothDevice.uuids[0].toString())

Or this one?

scanResult.scanRecord.serviceUuids, which prints to null.

Both?

**Comment by dariuszseweryn** [comment]
Closing as there is [a related general usage question on Stackoverflow](https://stackoverflow.com/questions/55392077)
