### ISSUE TITLE
Sample app broken by change in rxbinding library

### ISSUE THREAD

**Issue by RobLewis** [Polidea/RxAndroidBle#564]
It appears that a change in Jake Wharton's `rxbinding` library has caused a compile error in the sample app. The class `AdvancedCharacteristicOperationExampleActivity.java` has a failed import: 
`import com.jakewharton.rxbinding3.view.RxView;` 

I'm not familiar enough with the code to identify the exact cause of the error, but the method `activatedClicksObservable` can't resolve `RxView`.

**Comment by dariuszseweryn** [comment]
Hmmm... I just built and ran the app without issues. Are you sure that a `Gradle Sync` (File => Sync Project with Gradle Files) was run after you have pulled the changes?

**Comment by RobLewis** [comment]
Didn't know that it was necessary to explicitly sync, as it seems to me that it normally happens automatically? Anyway, that seems to have fixed it.

**Comment by dariuszseweryn** [comment]
From my knowledge it should happen automatically. Good that it is solved.
