### ISSUE TITLE
How to detect removed devices while scanning

### ISSUE THREAD

**Issue by mars3142** [Polidea/RxAndroidBle#57]
Is there a way to see, if a device is out of range while scanning?

I always get devices and they are always visible. But how do I handle devices, which are going offline while scanning? I need to cleanup my list.

**Comment by dariuszseweryn** [comment]
I believe this question should go on stackoverflow.com with the tag `rxandroidble` as it may possibly benefit more people.
Long story short - you should filter out devices that were not scanned (seen) for a period of time.
