### ISSUE TITLE
Can't scan to device on the phone that close system log

### ISSUE THREAD

**Issue by xaxasemail** [Polidea/RxAndroidBle#571]
I notice that the system log is closed in default on some phone like chinese phone meilan s6 . And can't scan to any device on that phone.How could I solve the problem? Thanks.

**Comment by dariuszseweryn** [comment]
Hello,

Could you describe what you are facing in a bit more detail way?
I do not have access to the phone you mentioned. Check if no errors are captured during the scan.
I am not sure what you reference by:
> I notice that the system log is closed in default

**Comment by xaxasemail** [comment]
The system log switch button is a switch button in Developer options ,we could print log in android studio when you turn it on.
Once we turn it off, we could not get the log from Log.d("asdf") in android studio cause we turn it off.
In a word, the switch button could control the output of the log.
I see , the function is less common on android phone. so very few people pay attention to this. Some huawei phones also have this function , but the switch button is in Engineering mode.

**Comment by dariuszseweryn** [comment]
Is there any problem with turning the logs on for debugging purposes? If so you can set your custom logger to check the library logs.
If something goes really wrong you would get an error in the `.subscribe()` function callback.

**Comment by xaxasemail** [comment]
My problem is that some devices cannot be scanned when the log is turned off, and the log switch on some Chinese mobile phones is turned off by default, so I wonder if I can normally scan the device when the log is turned off.

**Comment by dariuszseweryn** [comment]
I see no reason why one thing would interfere with another

**Comment by dariuszseweryn** [comment]
I can only see one reason for this to happen. _If_ a call to any `Log` method would throw a `RuntimeException` but it seems unlikely. Feel free to dig deeper into the issue and report back if you find a culprit.

**Comment by dariuszseweryn** [comment]
@xaxasemail Any news?

**Comment by dariuszseweryn** [comment]
Closing due to lack of information and inactivity of the original poster.

When more data will be available—feel free to add that information and reopen this issue.

Best Regards
