### ISSUE TITLE
Scanning in background

### ISSUE THREAD

**Issue by pfives** [Polidea/RxAndroidBle#58]
Awesome library.

I'm curious as to how you guys recommend scanning when the app is backgrounded. Generally I'm scanning in a service that keeps running even after the app is backgrounded. I know in `Android 5.0`(?) they added a `LOW_POWER_MODE` or something to that effect for scanning and wondering if you guys leverage this? Or generally what your thoughts are on the best way to scan using `RxAndroidBle` while backgrounded. Thanks!

**Comment by dariuszseweryn** [comment]
Hello there,
Currently the library does not use scanning methods introduced in API 21. We have an issue created for the feature #16 
So as for now it is not recommended to do scanning in the background as prolonged scans using API 18 are sometimes causing the whole Android BLE stack to malfunction. But if you really have to do it - you have no other option than to use it.
Pull requests are always welcome. ;)
Best Regards
