### ISSUE TITLE
autoConnect 

### ISSUE THREAD

**Issue by houyuehai** [Polidea/RxAndroidBle#580]
The autoConnect function is to connect when available, but can we set it up to try to connect automatically after disconnection?

**Comment by dariuszseweryn** [comment]
Hello!

Thank you for using the library.

This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rxandroidble) with `rxandroidble` tag—it will be easier to find by other users. Also feel free to check already posted questions as a similar one may be already answered.

Best Regards
