### ISSUE TITLE
BLE long read (> 600 bytes)

### ISSUE THREAD

**Issue by GuillaumeLefevre** [Polidea/RxAndroidBle#582]
Hello,

### Summary
I'm struggling with reading data longer than 600 bytes..
I tried the solution of this post with no result: https://stackoverflow.com/questions/48741196/android-ble-client-only-returns-600-byte-of-data-in-oncharacteristicread

The last bytes are getting discarded whatever MTU i'm using (any relation with the MTU ?).

MTU | Data length
---|---
247 (Max of my ble device) | 600
201 | 514
200 | 512
185 (iOS MTU) | 482
151 | 414
101 | 300
92 | 273
61 | 180
51 | 150
23 (Min of my ble device) | 66

It's working well on MAC and iOS (BlueSee / Nrf Connect), i'm getting 512 bytes on the first read and the remaining chunks in a second read.

I don't know if it's a side effect of the library or not...
Any idea ?

### Library version
`1.10.0`

#### Preconditions
You need to have a characteristic having data of a size of more than 600 bytes.

#### Steps to reproduce actual result
<br />Read characteristic -> Gives you the first 600 bytes as specified by Android
<br />Read characteristic -> Returns nothing

#### Minimum code snippet reproducing the issue
I'm using this custom operation to send read characteristics as long as i have data : (still in development)

```kotlin
class LongReadOperation(private val characteristic: BluetoothGattCharacteristic,
                        private val size: Int) : RxBleCustomOperation<ByteArray> {

	private var readLength = 0
	private var count = 0

	override fun asObservable(bluetoothGatt: BluetoothGatt, rxBleGattCallback: RxBleGattCallback, scheduler: Scheduler): Observable<ByteArray> {

		return Observable.create { emitter ->

			var bytes = byteArrayOf()

			// MTU
			val mtuDisposable = rxBleGattCallback.onMtuChanged
					.subscribeOn(scheduler)
					.subscribe {
						Log.e("TAG", "On Mtu changed : $it")
						bluetoothGatt.discoverServices()
					}

			// Discover
			val discoverDisposable = rxBleGattCallback.onServicesDiscovered
					.subscribeOn(scheduler)
					.subscribe {
						Log.e("TAG2", "On services discovered")
						readLength = 0
						Log.e("TAG", "Read length : $readLength | Send read")
						bluetoothGatt.readCharacteristic(characteristic)
					}

			// Read
			var readDisposable: Disposable? = null
			readDisposable = rxBleGattCallback.onCharacteristicRead
					.subscribeOn(scheduler)
					.doOnSubscribe {
						Log.e("TAG2", "Subscribed onCharacteristicRead")
					}
					.doOnNext {
						count++
					}
					.doOnComplete {
						emitter.onComplete()
					}
					.subscribe({
						val data = it.second
						Log.i("TAG2", "Wanted size = $size : On Read : ${data.size} Current read length : $readLength")
						Log.d("TAG2", "On read data : ${HexString.bytesToHex(data)}")

						if (readLength == 0) {
							readLength = data.size
							Log.e("TAG2", "Read length = 0 | new Length : $readLength")
							bytes = byteArrayOf()
							bluetoothGatt.readCharacteristic(characteristic)
						} else {
							bytes.plus(data)
							readLength -= data.size

							if (readLength == 0 || count >= 3) {
								Log.e("TAG2", "Got all data")
								// Got all data this time; you can now process the data however you want
								readDisposable?.dispose()
								discoverDisposable.dispose()
								mtuDisposable.dispose()

								emitter.onNext(bytes)
								emitter.onComplete()
							} else {
								Log.e("TAG2", "Read again")
								bluetoothGatt.readCharacteristic(characteristic)
							}
						}
					}, {
						readDisposable?.dispose()
						discoverDisposable.dispose()
						mtuDisposable.dispose()
						it.printStackTrace()

						emitter.onError(it)
					})

			/*
			When the maximum size of Data field is 27 bytes,
			this allows for maximum transfer of 23 bytes of ATT data per BLE Packet.

			iPhone 6 and 6S ATT_MTU is 185. This results in 3/185 or 1.6% of header overhead
			for a payload of 182 bytes. L2CAP will transfer 185/23 or 9 Link Layer Packets.

			When the ATT_MTU is 23, the payload of 185 bytes will be fragmented
			into 185/20 or 10 ATT packets, which results in 8 Link Layer packets.

			MTU -> Data length
			247 (MAX) -> 600
			201 -> 514
			200 -> 512
			185 -> 482
			151 -> 414
			101 -> 300
			92 -> 273
			61 -> 180
			51 -> 150
			23 (MIN) -> 66*/
			bluetoothGatt.requestMtu(200)
		}
	}
}
```

#### Logs from the application running with setting `RxBleLog.setLogLevel(RxBleLog.VERBOSE)`
```
D/BluetoothGatt: configureMTU() - device: 00:0D:6F:23:2F:FA mtu: 200
D/BluetoothGatt: onConfigureMTU() - Device=00:0D:6F:23:2F:FA mtu=200 status=0
E/TAG: On Mtu changed : 200
D/BluetoothGatt: discoverServices() - device: 00:0D:6F:23:2F:FA
D/BluetoothGatt: onSearchComplete() = Device=00:0D:6F:23:2F:FA Status=0
E/TAG2: On services discovered
E/TAG: Read length : 0 | Send read
I/TAG2: Wanted size = 606 : On Read : 512 Current read length : 0
D/TAG2: On read data : A96B4170706C69636174696F6E9F6856656E657469616EA36177F561658466526F6C6C65726856656E657469616E655A65627261655368656572616966526F6C6C6572FF715265766572736564446972656374696F6E9FF4A26177F56169F4FF694C69667452616E67659FF6A56177F5616C186E6168196B6C61756570756C7365616900FF6954696C7452616E67659FF6A56177F5616C0061681903E861756570756C7365616900FF6E54696C7446726F6D426F74746F6D9FF4A26177F56169F4FF6A55704261A56177F5616C0061681903E86175626D7361691823FF7819496E7465726D656469617465506F736974696F6E734C6966749F9F9FF6A261756125616900FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FFFFA26177F5616810FF7819496E7465726DFF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FF9FF6A161756125FFFFA26177F5616810FF
E/TAG2: Read length = 0 | new Length : 512
I/TAG2: Wanted size = 606 : On Read : 0 Current read length : 512
D/TAG2: On read data :
```
#### Actual result
I know before starting to read how much data i'm gonna get (606). Steps : 
- Set the MTU to 200
- Discover services (not very useful because i already have the gatt characteristic in the constructor)
- Read characteristic -> Returns 600 bytes
- Read characteritic -> Returns nothing, remaining bytes are discarded

I use 200 as a MTU in this example but i have the same result for every MTUs in the comments..
I think the device is sending me all of the data but Android is not able to read everything or discarding data after 600 bytes..

#### Expected result
The second read should give me the last bytes.

GL

**Comment by dariuszseweryn** [comment]
Hello,

Thank you for using the library.
Your post seems to be a bug report but it lacks some crucial information. Could you edit to contain information according to the [issue template](https://github.com/Polidea/RxAndroidBle/blob/master/.github/ISSUE_TEMPLATE.md)?

Best Regards

**Comment by GuillaumeLefevre** [comment]
@dariuszseweryn Sry about that, just edited my post :)

**Comment by dariuszseweryn** [comment]
According to Core `BLUETOOTH SPECIFICATION Version 5.0 | Vol 3, Part F`, `3.2.9 Long Attribute Values`:

> The maximum length of an attribute value shall be 512 octets.

Having longer values is against specification and it is hard to say what will happen

**Comment by dariuszseweryn** [comment]
From what I see the output is more or less according to what you have implemented judging from the code snippet. First of all I do not see a reason to create a custom operation for this one but just subscribe two times to the `readCharacteristic()` observable. Anyway this is not an issue with the library. This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rxandroidble) with `rxandroidble` tag—it will be easier to find by other users. Also feel free to check already posted questions as a similar one may be already answered.

**Comment by VictorVanWeyenberg** [comment]
Also bluetooth spec, couple of lines above the line you quotes, it says:

> An attribute value may be defined to be larger than (ATT_MTU-1) octets in size. These attributes are called long attributes. To read the entire value of an attributes larger than (ATT_MTU- 1) octets, the ATT_READ_BLOB_REQ PDU is used. It is possible to read the first (ATT_MTU-1) octets of a long attribute value using the ATT_READ_REQ PDU.

Although the max value length of a characteristic is 512 bytes, this blob behaviour can be used to extend that length to 65536 bytes theoratically.

I've seen this being supported in blueZ. Some tests I ran there only yielded success if I kept my value length around 32kB.

**Comment by jci-zimm** [comment]
Anyone know how to get past this 600 byte limitation? I tried changing `ESP_GATT_MAX_ATTR_LEN` [here](https://github.com/espressif/esp-idf/blob/3441dd1e9832a99dbd823e7dc73700169815772f/components/bt/host/bluedroid/api/include/api/esp_gatt_defs.h#L295) and `GATT_MAX_ATTR_LEN` [here](https://github.com/espressif/esp-idf/blob/1cb31e50943bb757966ca91ed7f4852692a5b0ed/components/bt/host/bluedroid/stack/include/stack/gatt_api.h#L137) and `BTA_GATTC_CACHE_SRVR_SIZE` to a larger size without luck. Is there something beneath bluedroid on the ESP32 that is hardcoded to 600?
