### ISSUE TITLE
compile fail in android studio 3.4

### ISSUE THREAD

**Issue by sqken** [Polidea/RxAndroidBle#590]
Method com/github/jengelman/gradle/plugins/shadow/internal/DependencyFileCollection.getBuildDependencies()Lorg/gradle/api/tasks/TaskDependency; is abstract

**Comment by dariuszseweryn** [comment]
Related [stackoverflow question](https://stackoverflow.com/questions/56592289/fail-to-compile-https-github-com-polidea-rxandroidble)
