### ISSUE TITLE
Dealing with max connections

### ISSUE THREAD

**Issue by mrf7** [Polidea/RxAndroidBle#594]
Android devices have a limit on the maximum number of connections which varies greatly by device. The native library's behavior when connecting to a new device while you have maximum connections. Does this library have a define behavior in this case? I'm trying to maintain periodic communication with many devices at once by cycling through the devices and want to be able to react to reaching this maximum.

**Comment by dariuszseweryn** [comment]
This library has no defined behaviour for this case. It will pass the exception from the system so normal Android behaviour applies
