### ISSUE TITLE
[Question] Keeping GATT connection open

### ISSUE THREAD

**Issue by mattinger** [Polidea/RxAndroidBle#599]
### Summary

I was trying to determine from the API if it's possible to keep a gatt connection open outside of the lifecycle of the establishConnection observable.  Or is the connection closed once there are no more subscribers.  I'm basically trying to wrap things up in kotlin coroutines:

```kotlin
suspend fun RxBleDevice.connectGatt(autoConnect: Boolean): RxBleConnection =
    suspendCancellableCoroutine<RxBleConnection> { continuation ->
        val disposable = establishConnection(autoConnect).subscribe(
            { conn -> continuation.resume(conn) },
            { throwable -> continuation.resumeWithException(throwable) })

        continuation.invokeOnCancellation {
            if (!disposable.isDisposed) {
                disposable.dispose()
            }
        }
    }
```

I'm just unsure if the connection would even be usable once this coroutine resumed.  I don't see anything in the `establishConnection` function which would be closing the gatt connection, but there's several layers of watchers and things that are involved in that.

This is a great library and handles just about everything correctly.  The only thing is that we are moving away from Rx toward coroutines, so i'd like to create a coroutine interface to this library.

Even if we don't wrap, we have to do some reads, then make an api call, then write data back.  The api calls or executed through coroutines, so it's not a simple task to use flatmapping, zipping, etc...

```RxBleDevice.establishConnection() is an Observable that will emit a single RxBleConnection but will not complete as the connection may be later a subject to an error (i.e. external disconnection). Whenever you are no longer interested in keeping the connection open you should dispose it which will cause disconnection and cleanup of resources.```

This leads me to believe that the connection can stay open as long as the returned disposable is open.

### Library version
`1.10.1`

**Comment by dariuszseweryn** [comment]
> This leads me to believe that the connection can stay open as long as the returned disposable is open.

Correct. Just have in mind that this `Disposable` is the only handle to explicitly disconnect your peripheral. If you need to cancel the connection at any point you should return `Pair<RxBleConnection, Disposable>` from the coroutine.

Or even make the `RxBleConnection` a `CoroutineContext`/`CoroutineScope` somehow as if the connection will ever be broken (and that may happen asynchronously at any moment) all further actions on the `RxBleConnection` will fail. I am not familiar enough with coroutines to give a concrete example, I just think it should be feasible.

**Comment by dariuszseweryn** [comment]
If there are no more questions I will close this thread.
Feel free to share your solution as it may be helpful for some.

Best regards
