### ISSUE TITLE
OnErrorNotImplementedException on disconnect

### ISSUE THREAD

**Issue by PieterAelse** [Polidea/RxAndroidBle#600]
We're encountering multiple crashes of `OnErrorNotImplementedException` in our production app. So I have no steps to reproduce, but I'll mention as much info as I can.

### Library version
`1.10.1`

#### Actual result
`OnErrorNotImplementedException` is thrown

#### Expected result
`onError` handler should be present in the `subscribe()` 

#### Devices

- Samsung Galaxy Note 9, Android 9
- Motorola G4 Play, Android 7.1.1
- Motorola Moto G6 Play, Android 8.0.0
- Google Pixel 3XL, Android 9
- Samsung Galaxy Note 8, Android 9

#### Stacktrace

> Fatal Exception: io.reactivex.exceptions.OnErrorNotImplementedException
> The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAC='XX:XX:XX:XX:XX:XX' with status 8 (GATT_INSUF_AUTHORIZATION or GATT_CONN_TIMEOUT)
> io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept (Functions.java:704)
> io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept (Functions.java:701)
> io.reactivex.internal.observers.ConsumerSingleObserver.onError (ConsumerSingleObserver.java:46)
> io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run (SingleObserveOn.java:79)
> io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run (HandlerScheduler.java:124)
> android.os.Handler.handleCallback (Handler.java:873)
> android.os.Handler.dispatchMessage (Handler.java:99)
> android.os.Looper.loop (Looper.java:214)
> android.app.ActivityThread.main (ActivityThread.java:6981)
> java.lang.reflect.Method.invoke (Method.java)
> com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
> com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)
> 

> Caused by com.polidea.rxandroidble2.exceptions.BleDisconnectedException
> Disconnected from MAC='XX:XX:XX:XX:XX:XX' with status 8 (GATT_INSUF_AUTHORIZATION or GATT_CONN_TIMEOUT)
> com.polidea.rxandroidble2.internal.connection.RxBleGattCallback$2.onConnectionStateChange (RxBleGattCallback.java:80)
> android.bluetooth.BluetoothGatt$1$4.run (BluetoothGatt.java:313)
> android.bluetooth.BluetoothGatt.runOrQueueCallback (BluetoothGatt.java:876)
> android.bluetooth.BluetoothGatt.access$200 (BluetoothGatt.java:43)
> android.bluetooth.BluetoothGatt$1.onClientConnectionState (BluetoothGatt.java:308)
> android.bluetooth.IBluetoothGattCallback$Stub.onTransact (IBluetoothGattCallback.java:71)
> android.os.Binder.execTransact (Binder.java:739)

**Comment by dariuszseweryn** [comment]
You probably forgot to put an `onError` handler somewhere in your `.subscribe()`

**Comment by dariuszseweryn** [comment]
You're welcome ;)
