### ISSUE TITLE
NotifyClick not working 

### ISSUE THREAD

**Issue by manishpatelgt** [Polidea/RxAndroidBle#611]
I am trying below code from sample app.

 ```
if (isConnected()) {
            final Disposable disposable = connectionObservable
                    .flatMap(rxBleConnection -> rxBleConnection.setupNotification(characteristicUuid, NotificationSetupMode.QUICK_SETUP))
                    .doOnNext(notificationObservable -> runOnUiThread(this::notificationHasBeenSetUp))
                    .flatMap(notificationObservable -> notificationObservable)
                    .retryWhen(errors -> errors.flatMap(error -> {
                        if (error instanceof BleDisconnectedException) {
                            Log.d("Retry", "Retrying");
                            return Observable.just(null);
                        }
                        return Observable.error(error);
                    }))
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(this::onNotificationReceived, this::onNotificationSetupFailure);

            compositeDisposable.add(disposable);
```

As soon as press Register Notifications button I am always getting error like below

![Screenshot_20190918-112512](https://user-images.githubusercontent.com/7836990/65125440-fcf9b300-da12-11e9-9748-81623996d175.png)
![Screenshot_20190918-112828](https://user-images.githubusercontent.com/7836990/65125441-fd924980-da12-11e9-94bc-c71bfd928927.png)

How to resolve this ? How do I enable notification for that characteristicUuid ?

**Comment by dariuszseweryn** [comment]
I do not know — you did not include logs as issue template asks you to

**Comment by manishpatelgt** [comment]
@dariuszseweryn  I am adding logs in 10 min

**Comment by manishpatelgt** [comment]
@dariuszseweryn 
Logs 

> t: setCharacteristicNotification() - uuid: 0000ffe1-0000-1000-8000-00805f9b34fb enable: true
> 2019-09-18 14:49:43.371 15811-15811/com.polidea.rxandroidble.sample D/BluetoothGatt: setCharacteristicNotification() - uuid: 0000ffe1-0000-1000-8000-00805f9b34fb enable: false
> 2019-09-18 14:49:43.377 15811-15811/com.polidea.rxandroidble.sample I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
> 2019-09-18 14:49:43.382 15811-15811/com.polidea.rxandroidble.sample I/System.out: Notifications error: com.polidea.rxandroidble2.exceptions.BleCannotSetCharacteristicNotificationException: Cannot find client characteristic config descriptor (code 2) with characteristic UUID 0000ffe1-0000-1000-8000-00805f9b34fb

**Comment by dariuszseweryn** [comment]
`com.polidea.rxandroidble2.exceptions.BleCannotSetCharacteristicNotificationException: Cannot find client characteristic config descriptor (code 2) with characteristic UUID 0000ffe1-0000-1000-8000-00805f9b34fb`
As you can see your peripheral does not conform to the Bluetooth Core Specification. It has no `Client Characteristic Configuration Descriptor`. There are specific modes for setting notifications in such cases. See `NotificationSetupMode`.

**Comment by manishpatelgt** [comment]
@dariuszseweryn  How to do this with this sample ?

**Comment by dariuszseweryn** [comment]
Change `RxBleConnection.setupNotification()` call to use a proper `NotificationSetupMode`. Or preferably fix the peripheral so it will include `Client Characteristic Configuration Descriptor` according to the Bluetooth Spec

**Comment by manishpatelgt** [comment]
@dariuszseweryn  Worked well now. Before I am using **NotificationSetupMode.QUICK_SETUP** and after updating to **NotificationSetupMode.COMPAT**.

Thanks for your little help

**Comment by guodi1014** [comment]
I have also encountered the same problem, which is indeed an effective solution. It seems that not all device manufacturers will configure according to standards.  Thank you !
