### ISSUE TITLE
Make Client Characteristic Config configurable

### ISSUE THREAD

**Issue by AdrianGlasnapp** [Polidea/RxAndroidBle#616]
Currently NotificationAndIndicationManager uses hardcoded value for Client Characteristic Config (**00002902-0000-1000-8000-00805f9b34fb**). Some devices expose custom descriptors for notifications and because of hardcoded value there is no possibility to register for such notifications. 

Is it reasonable to pass custom descriptor to `setupNotification`?
`
setupNotification(uuid, customDescriptor)
`

**Comment by dariuszseweryn** [comment]
I have not seen such a case — could you give more details?

**Comment by mkonkel** [comment]
Got the same situation on some custom BT device.

**Comment by mkonkel** [comment]
![Capture+_2019-09-20-08-17-59](https://user-images.githubusercontent.com/7625396/65303821-5aab0e00-db7f-11e9-8c50-1d3ad71b192e.png)

**Comment by dariuszseweryn** [comment]
Ok, so there is a custom descriptor I get it — but what is the reasoning of having such?

**Comment by mkonkel** [comment]
dunno, manufacturer decision, I know it's strange but I can't change it.

**Comment by dariuszseweryn** [comment]
Answering the question:
> Is it reasonable to pass custom descriptor to `setupNotification`?

No, it is not reasonable to do so. It is against the Core Bluetooth Specification.

Adding such customisation would most probably also need specifying custom on/off data or other behaviours. Afterwards this custom solution would need to be maintained or extended for other against-the-standard solutions.

Current library API allows for creating a flow that would fit your needs — I do not see a reason for introducing new API that promotes breaking specification.

Best Regards
