### ISSUE TITLE
How to disconnect from a peripheral?

### ISSUE THREAD

**Issue by anikdey** [Polidea/RxAndroidBle#629]
I have posted the sample code here in

[StackOverflow](https://stackoverflow.com/questions/58412394/com-polidea-rxandroidble2-exceptions-blescanexception-scan-failed-because-appli)

And another question. What is the proper way to be disconnected from a ble device.?

**Comment by ryanmitchener** [comment]
Is your GS8 running Android 10?

**Comment by anikdey** [comment]
No. Android 9.

**Comment by dariuszseweryn** [comment]
> What is the proper way to be disconnected from a ble device.?

As [Readme states](https://github.com/Polidea/RxAndroidBle#observable-behaviour) — dispose the `Observable<RxBleConnection>`.

Stackoverflow questions will not be discussed here.

Best Regards
