### ISSUE TITLE
writeCharacteristic take too much time on some devices, help needed

### ISSUE THREAD

**Issue by IvanKnyaziev** [Polidea/RxAndroidBle#638]
I'm facing an issue with writeCharacteristic
```
        deviceHolder.device.rxBleConnection?.let { connection ->
            connection.writeCharacteristic(UUID.fromString(BluetoothCharacteristic.MOTOR_VALUE.value), bytes)
                    .subscribeOn(Schedulers.io())
                    .subscribe({ deviceHolders.getItem(macAddress)?.device?.isMotorPlaying = true }, error)
                    .let { deviceHolder.valuesDisposable = it }
        } 
```
"bytes" is an array with 7 bytes `[1, 10 ,67 ,50 ,11 ,50 ,34]`
I'm writing this array every 96ms and it works perfect for example on One Plus, but on some devices like Samsung S8 I'm facing a long delay, I tried to measure time between execution and sometimes it takes 96ms(perfect) and sometimes 500ms or even more, as a result toy control start delay and this delay increasing. Please help with an advice or maybe I'm doing something wrong. I can provide more info if needed.
ver 1.9.1 in use

**Comment by dariuszseweryn** [comment]
Hello!

Thank you for using the library.

This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rxandroidble) with `rxandroidble` tag—it will be easier to find by other users. Also feel free to check already posted questions as a similar one may be already answered.

Best Regards

P.S. Check what are connection parameters are and/or set connection priority
