### ISSUE TITLE
setupNotification - Observable or Single?

### ISSUE THREAD

**Issue by valeriyo** [Polidea/RxAndroidBle#641]
This is confusing:
```
/**
 * @return Observable emitting another observable when the notification setup is complete.
 */
Observable<Observable<byte[]>> setupNotification(@NonNull UUID characteristicUuid, @NonNull NotificationSetupMode setupMode);
```
Why is this not `Single<Observable<byte[]>>` ?

**Comment by dariuszseweryn** [comment]
https://github.com/Polidea/RxAndroidBle#observable-behaviour

**Comment by valeriyo** [comment]
Thanks for the link. Nonetheless, it should be `Single<Observable<byte[]>>` - the subscription to the emitted `Observable<byte[]>` should be sufficient to manage resources.

**Comment by dariuszseweryn** [comment]
Sometimes there is a use case when there are no subscribers to `Observable<byte[]>` but the user does not want to notify the peripheral about it

**Comment by valeriyo** [comment]
Not sure I understand. You are saying that there are use-cases when one would subscribe to the outer `Observable<Observable<byte[]>>` but not to the inner `Observable<byte[]>`?

**Comment by dariuszseweryn** [comment]
Yes. Imagine that the inner `Observable<byte[]>` gets subscribed at various times depending on other factors but the BLE notification (as a side effect) is expected to be continuous.

**Comment by dariuszseweryn** [comment]
Does it answer your question @valeriyo ? Do you have an idea on how to address this case differently?

**Comment by valeriyo** [comment]
Yes, thanks for following up. I'm planning to use `RxAndroidBle` for scanning - because it seems to work very well, but for data (connecting/writing/reading) - I found the `RxAndroidBle` APIs too cumbersome to use (managing observables subscriptions, and the UndeliverableException, which is actually the `RxAndroidBle`'s fault - it shouldn't emit errors when there are no subscribers). So, I'll stick with `nordicsemi` for now. Thanks.

**Comment by dariuszseweryn** [comment]
> I found the RxAndroidBle APIs too cumbersome to use

I am afraid that I cannot do much with this. You are always welcome to give constructive feedback. Best regards
