### ISSUE TITLE
How to connect with multi device by using RxAndroidBle?

### ISSUE THREAD

**Issue by Cetger** [Polidea/RxAndroidBle#657]
Is there any example which can work with multi device? I read post on Stackoverflow. I saw some questions but there was no example about this. Unfortunately, some people are new at Embedded programming like me. To be honest, I learned almost new how to work Bluetooth. 
Suppose that I have a 2 string UUID as String deviceOne and String deviceTwo. Dont care to scan or something like that. I have these strings in an activity. When I want to connect with thee devices, what I must do. All I need is a blank working demo. 
Thanks is advanced.

**Comment by dariuszseweryn** [comment]
Hello!

Thank you for using the library.

This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rxandroidble) with `rxandroidble` tag—it will be easier to find by other users. Also feel free to check already posted questions as a similar one may be already answered.

Best Regards
