### ISSUE TITLE
How to turn off toast message appears from SDK ?

### ISSUE THREAD

**Issue by manishpatelgt** [Polidea/RxAndroidBle#658]
I want to turn off such connection message appears in form of Toast from SDK ?

![image](https://user-images.githubusercontent.com/7836990/71799052-3154b600-307a-11ea-968f-c7da39fa8a16.png)

I am using

`  implementation "com.polidea.rxandroidble2:rxandroidble:1.10.1"`

Sorry tagged this as BUG but actually it's not.

**Comment by dariuszseweryn** [comment]
You should remove all `Toast` references from your code. The library does not use `Toast` by itself.
