### ISSUE TITLE
Error Building Project When Import It

### ISSUE THREAD

**Issue by zawawimanja** [Polidea/RxAndroidBle#660]
**Error**

**To Reproduce**
1. Import project 
2. Build it

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pocophone]
 - OS: [e.g. Android 9]
 - Library version: [e.g. 1.10.5]

```
// Checkstyle rule violations were found. See the report at: file:///C:/Users/manja/Downloads/RxAndroidBle-master/rxandroidble/build/reports/checkstyle/checkstyle.html
Checkstyle files with violations: 1
Checkstyle violations by severity: [error:1]
```

**Additional context**

**Comment by dariuszseweryn** [comment]
Locally everything seems to work fine for me so I assume you are using a Windows machine. If that is the case you should use LF instead of CRLF as EOL marker. See #655 and #567 

Best Regards

P.S. If this will not help — you could try running `gradlew checkstyle` and paste the exact error message.
