### ISSUE TITLE
Does the library support passkey entry? 

### ISSUE THREAD

**Issue by vtatntpt** [Polidea/RxAndroidBle#667]
**Hello, Does the library support passkey entry? I did not find in the document Thanks..**

**Comment by dariuszseweryn** [comment]
All bonding related operations are handled by the OS

**Comment by dariuszseweryn** [comment]
I have created a [wiki page about bonding](https://github.com/Polidea/RxAndroidBle/wiki/FAQ:-Bonding). Hope it will help you and other users.
