### ISSUE TITLE
How do i get RSSI even after connected to BLE ?

### ISSUE THREAD

**Issue by manishpatelgt** [Polidea/RxAndroidBle#671]
I am using 

`   implementation "com.polidea.rxandroidble2:rxandroidble:1.11.0"`

I want to get RSSI even after connected to BLE device. I saw after connected to BLE device when i scan again i don't see my connected ble device appears in the scan list. 

So is that possible to get RSSI for connected BLE device using this lib?

**Comment by dariuszseweryn** [comment]
> So is that possible to get RSSI for connected BLE device using this lib?

Yes. Check `RxBleConnection` API

**Comment by labteleco** [comment]
How to use it?

**Comment by dariuszseweryn** [comment]
There is an API without any parameters. I am not sure what you ask about.

**Comment by manishpatelgt** [comment]
This is what I am looking for

[RssiPeriodicExampleActivity](https://github.com/Polidea/RxAndroidBle/blob/master/sample/src/main/java/com/polidea/rxandroidble2/sample/example5_rssi_periodic/RssiPeriodicExampleActivity.java)

thanks @dariuszseweryn
