### ISSUE TITLE
"Read and write combined" example broken

### ISSUE THREAD

**Issue by ChrisSDC** [Polidea/RxAndroidBle#674]
**Describe the bug**
The "[Read and write combined](https://github.com/Polidea/RxAndroidBle#read-and-write-combined)" example appears to be build-broken.

![image](https://user-images.githubusercontent.com/29198970/77063219-3b2d5a80-69d5-11ea-9f49-41804994c5d9.png)

**To Reproduce**
1. Copy/paste example
2. Set up appropriate variables

**Setup:**
 - Library version: 1.5.0 & 1.11.0
 - Android Studio version: 3.6.1
 - JDK version 1_8 (Java 8)

**Additional context**
I'm very new to ReactiveX so this could be a very simple syntax issue or even a setup issue on my part (apologies if that's the case), but a fix will be useful for other noobs such as myself.

**Comment by dariuszseweryn** [comment]
Yup. It should be `.doOnSuccess()`. Will fix Today

**Comment by dariuszseweryn** [comment]
@ChrisSDC Thank you for this report. It is now fixed.
