### ISSUE TITLE
Background Proccess

### ISSUE THREAD

**Issue by chandrabezzo** [Polidea/RxAndroidBle#684]
When I connect, write, and notify using backgorund service, connection running well but when I closed the application connection between service and BLE device lost.

**Comment by dariuszseweryn** [comment]
I believe you want to learn about how Android OS manages processes, when it closes them and what are foreground services.

**Comment by chandrabezzo** [comment]
I was learn about Android background proccess using Work Manager, IntentService, and Service. When I use GPS on background proccess, the GPS still connected with service. But when I use Bluetooth on background proccess using this library to connect BLE device, connection lost when application closed.

**Comment by dariuszseweryn** [comment]
It all depends on how you implement the service. If the service is started and in foreground then the connection should persist until the OS kills the service process.
If you close the application all application processes are killed thus ending the connection (I may be oversimplicating in some details here)

**Comment by chandrabezzo** [comment]
That resolved when I used foreground service, thank you.
