### ISSUE TITLE
Connection BLE

### ISSUE THREAD

**Issue by chandrabezzo** [Polidea/RxAndroidBle#685]
I was connect BLE using establishConnection with autoConnect false. Then, I add  connection to disposable and compose to replaying share the connection. 
```
connect = bleClient.getBleDevice(viewmodel.selectedDevice())
                        .establishConnection(false)

connection = connect.compose(ReplayingShare.instance())
connectionDisposable = connect.subscribe()
```
Using that code I was connected application to BLE Device, but when I try to disconnect from activity using dispose connectionDisposable.dispose() the connection still connect. Please tell me If my code is wrong to connect application with BLE device.

**Comment by dariuszseweryn** [comment]
Hello!

Thank you for using the library.

This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rxandroidble) with `rxandroidble` tag—it will be easier to find by other users. Also feel free to check already posted questions as a similar one may be already answered.

Best Regards

P.S. You probably want to describe there what you want to achieve as well as it is not clear from the original post.
