### ISSUE TITLE
Finding device unique uuid

### ISSUE THREAD

**Issue by CanEmreUnal** [Polidea/RxAndroidBle#687]
Hi there!

I'm trying to get device unique uuid but returns null.

On the other hand i can get the identifier from mac&ios side. (PeripheralScanCallBack) 

Is there anyway to achive that identifier ? ( I cannot use mac adress because of we are using same database to check if device is registered or not ?)

```
//Scanning with deviceName
findDevice(deviceName).observeOn(AndroidSchedulers.mainThread())
                .doFinally {
                    //dispose()
                }
.subscribe(
                    {
                        //Problem is here ?!
                        device.uuid = it.bleDevice.bluetoothDevice.uuids.first().toString() ?: ""
                    },
                    {
                        onScanFailure(it)
                    })
```

**Comment by dariuszseweryn** [comment]
UUID as device identifier is Apple's concept. If you would read the Javadoc of `BluetoothDevice#uuids` you would probably figured it out by now.
