### ISSUE TITLE
how to connect  BLE device & send mtu request and get characteristic UUID of a service by Service UUID step by step

### ISSUE THREAD

**Issue by HosseinKurd** [Polidea/RxAndroidBle#693]
**Describe the bug**
I need to connect BLE device & send MTU request and get characteristic UUID of service by Service UUID step by step

**To Reproduce**
1. Find the BLE device by name or mac address
3. Send MTU request 517
4. Get service by Service UUID
5. Get characteristic value by characteristic UUID

**Additional context**
I can not combine all methods and unable to call one after one

**Comment by dariuszseweryn** [comment]
Hello!

Thank you for using the library.

This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rxandroidble) with `rxandroidble` tag—it will be easier to find by other users. Also feel free to check already posted questions as a similar one may be already answered.

Best Regards
