### ISSUE TITLE
When using the ValueInterpreter class, is there functionality for parsing values of specific sizes?

### ISSUE THREAD

**Issue by smkarber** [Polidea/RxAndroidBle#695]
In implementation of RxAndroidBle I am trying to get the vlue of out the [System ID characteristic](https://www.bluetooth.com/xml-viewer/?src=https://www.bluetooth.com/wp-content/uploads/Sitecore-Media-Library/Gatt/Xml/Characteristics/org.bluetooth.characteristic.system_id.xml) using the [ValueInterpreter helper class](https://github.com/Polidea/RxAndroidBle/blob/master/rxandroidble/src/main/java/com/polidea/rxandroidble2/helpers/ValueInterpreter.java).

The linked specification says that the value contained a 40-bit id and a 24-bit id, and I am trying to find a way to parse that value.

**Comment by dariuszseweryn** [comment]
Hey,

ValueInterpreter is for extracting standard 8, 16 and 32 bit floats/integers from characteristics to provide the same functionality that is available using Android's `BluetoothGattCharacteristic` class.

The link you provided describes which bytes contain which IDs — you simply copy appropriate bytes of the characteristic to get the ID you want.

From my understanding these IDs are not really _comparable_ with others but rather they are there so the user can _check_ if they are equal to some other ID. If that is the case you can simply use `Arrays.equals()`.

I hope my response helps you

**Comment by smkarber** [comment]
Thanks!
