### ISSUE TITLE
I'm struggling to implement a Bluetooth Scanner that obtains the advertising data from my Ibeacons

### ISSUE THREAD

**Issue by KyleAdo** [Polidea/RxAndroidBle#698]
Hello, I'm using this [repo](https://github.com/neXenio/BLE-Indoor-Positioning) that uses your library, but I'm currently struggling to scan for my Ibeacons. Here is the scanning Method here. Currently, it's not picking up my IBeacons and it explains in the Repo why that is, however, I'm not sure where to go from here in this method and how to make it scan for my Beacons. 

```
public static void startScanning() {
        if (isScanning()) {
            return;
        }

        final BluetoothClient instance = getInstance();
        Log.d(TAG, "Starting to scan for beacons");

        ScanSettings scanSettings = new ScanSettings.Builder()
                .setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY)
                .setCallbackType(ScanSettings.CALLBACK_TYPE_ALL_MATCHES)
                .build();

        instance.scanningSubscription = instance.rxBleClient.scanBleDevices(scanSettings)
                .subscribe(new Observer<ScanResult>() {
                    @Override
                    public void onCompleted() {

                    }

                    @Override
                    public void onError(Throwable e) {
                        Log.e(TAG, "Bluetooth scanning error", e);
                    }

                    @Override
                    public void onNext(ScanResult scanResult) {
                        instance.processScanResult(scanResult);
                    }
                });
    }
```
These are the modifications I made in this method.

```
ScanSettings scanSettings = new ScanSettings.Builder()
                    .setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY)
                    .setCallbackType(ScanSettings.CALLBACK_TYPE_ALL_MATCHES)
                    .build();
            ScanFilter scanFilter = new ScanFilter.Builder()
                    .setServiceUuid(UUID).build();
    
            instance.scanningSubscription = instance.rxBleClient.scanBleDevices(scanSettings, scanFilter)
                    .subscribe(new Observer<ScanResult>() {
                        @Override
                        public void onCompleted() {
                        }
    
                        @Override
                        public void onError(Throwable e) {
                            Log.e(TAG, "Bluetooth scanning error", e);
                        }
    
                        @Override
                        public void onNext(ScanResult scanResult) {
                            instance.processScanResult(scanResult);
                        }
                    });
```
As you can see I added a ScanFilter so it can find the UUID for my IBeacons and obtain the advertising data from them (which I then send to the process scan result method). But this implementation doesn't work, since it won't allow me to outright filter a UUID. 

I'm not sure if what I'm doing here is right, I've read the RxAndroidBle library repo readme but there isn't a lot to go on it and I can't get the app to scan for my specific Beacons. I have 4 IBeacons which are setup around my home, each Ibeacon I have has a UUID of "EBEFD083-70A2-47C8-9837-E7B5634DF524". 

How would I be able to get this method to correctly scan for that specific UUID or just wrap around the IBeacon's API's so I can obtain the necessary advertising data as the repo intends? I'm not 100% sure if I'm doing it correctly but I think I've got the right idea. Apologies if this is the wrong tag and too much infomation, I did post this problem on StackOverflow but unfortunately, nobody has responded and it hasn't got many views under these tags. But any help would be appreciated, thank you :)

**Comment by dariuszseweryn** [comment]
I believe [this](https://stackoverflow.com/questions/62470801/how-do-i-implement-a-bluetooth-scanner-that-obtains-the-advertising-data-from-my) is the related Stackoverflow question and answer.
