### ISSUE TITLE
What's the meanings of autoconnect?

### ISSUE THREAD

**Issue by tinybright** [Polidea/RxAndroidBle#7]
It's the normal meaning.
Or it's same as autoConnect in BluetoothDevice

    [ * @param autoConnect Whether to directly connect to the remote device (false)
     *                    or to automatically connect as soon as the remote
     *                    device becomes available (true).](url)

**Comment by mzgreen** [comment]
It's the same as `autoConnect` in BluetoothDevice. I think that it should be mentioned in the doc, do you agree @uKL ?

**Comment by uKL** [comment]
True, same meaning. Without auto connect the system will throw BleGattException with detail code 133. This will happen after some timeout, various on different devices.

With auto connect it will wait until the BLE device is available.

**Comment by farmazon3000** [comment]
#40 related.
