### ISSUE TITLE
Scan failed error in some devices

### ISSUE THREAD

**Issue by manishpatelgt** [Polidea/RxAndroidBle#719]
I am continuously getting error in my Motorola G7 phones. G7 running Android 9 version.

**Scan failed because application registration failed (code 6)**

I am using below version in my Android App

`implementation "com.polidea.rxandroidble2:rxandroidble:1.11.0"`

**Comment by dariuszseweryn** [comment]
Why do you think it is a library bug?

**Comment by dariuszseweryn** [comment]
Closing due to lack of information and inactivity of the original poster.

When more data will be available—feel free to add that information and reopen this issue.

Best Regards
