### ISSUE TITLE
pairing request dialog appears on every connection

### ISSUE THREAD

**Issue by tolot27** [Polidea/RxAndroidBle#730]
In our application we get every five minutes (at each communication with BLE devices) the bonding request dialog as shown in https://github.com/NightscoutFoundation/xDrip/issues/1494.

This behavior appears on devices with Android 10 (i. e. Pixel 3a, Samsung A50, S10, etc.) were the Android 2020-11-01 security patch level is installed (see here: https://github.com/NightscoutFoundation/xDrip/issues/1494#issuecomment-722176016_).

Is there an advice how to avoid this?

**Comment by dariuszseweryn** [comment]
Hello,
As you have linked to original issue. This does not seem to be a problem with the library but rather with the OS which manages bonding. I am afraid there is nothing can be done from the programmatic side of things.

**Comment by tolot27** [comment]
@dariuszseweryn Yes, you are right. Thx!
