### ISSUE TITLE
How can i subscribe to multiple notifications from different services UUID

### ISSUE THREAD

**Issue by kidney88** [Polidea/RxAndroidBle#731]
Hi there. I found the half of the answer.

    final UUID serviceUuid = // your service UUID
    final Map<UUID, byte[]> genericModel = new HashMap<>();
    final Observable<RxBleConnection> connectionObservable = // your connectionObservable

    connectionObservable
            .flatMap(connection -> 
                    connection.discoverServices()
                            .flatMap(services -> services.getService(serviceUuid).map(BluetoothGattService::getCharacteristics)) // get characteristics you're interested in
                            .flatMap(Observable::from) // deal with every characteristic separately
                            .flatMap(characteristic -> connection
                                            .setupNotification(characteristic) // setup notification for each
                                            .flatMap(observable -> observable), // to get the raw bytes from notification
                                    Pair::new) // merge characteristic with byte[] to keep track from which characteristic the bytes came
            )
            .subscribe(
                    pair -> genericModel.put(pair.first.getUuid(), pair.second),
                    throwable -> { /* handle errors */}
            ); 

But from one service UUID, i need to subscribe chars from two different services UUID. How can i reach that?

**Comment by dariuszseweryn** [comment]
Hello!

Thank you for using the library.

This is a general usage question and as such should be posted on [stackoverflow](https://stackoverflow.com/questions/tagged/rxandroidble) with `rxandroidble` tag—it will be easier to find by other users. Also feel free to check already posted questions as a similar one may be already answered.

Best Regards
