### ISSUE TITLE
Rxandroidble can’t find device already connected

### ISSUE THREAD

**Issue by lipu-ted** [Polidea/RxAndroidBle#740]
Hello there,
I have a problem when my device is connected by other apps. rxandroidble will not be able to search for this device. I want to know if it is the problem of rxandroidble? I want to be able to search for this device and connect even if the device is connected. Thank you

**Comment by dariuszseweryn** [comment]
If the device is connected it may not be scanned if it does not advertise anymore. You can check already connected BLE devices using `BluetoothManager` API and get it. After that you can retrieve an appropriate `RxBleDevice` from this lib and connect it.
