### ISSUE TITLE
UndeliverableException crashing the app but only on Samsung Phones

### ISSUE THREAD

**Issue by VinnyScorsatto** [Polidea/RxAndroidBle#750]
I use Crashlytics to monitor crashes and I am getting this one but just for Samsung phones. Any ideas? I have added error handling for all (connection, write, read, indication).

![Screen Shot 2021-05-10 at 9 19 25 AM](https://user-images.githubusercontent.com/58920139/117587755-870c0780-b173-11eb-9882-9e5e4e081789.png)
![Screen Shot 2021-05-10 at 9 18 21 AM](https://user-images.githubusercontent.com/58920139/117587757-883d3480-b173-11eb-8dd9-075c78e6af78.png)

Thanks

**Comment by dariuszseweryn** [comment]
This [wiki page](https://github.com/Polidea/RxAndroidBle/wiki/FAQ:-UndeliverableException) describes how to deal with all UndeliverableExceptions. This cannot be easily fixed without a total API rewrite. Original issue https://github.com/Polidea/RxAndroidBle/issues/383
