### ISSUE TITLE
Uncaught exception: SingleResponseOperation.timeoutFallbackProcedure

### ISSUE THREAD

**Issue by sigurdurrafn** [Polidea/RxAndroidBle#758]
An exception (SingleResponseOperation.timeoutFallbackProcedure, stack trace below) happens within RxAndroidBle causing our app to crash.

**To Reproduce**

This happens to some of our customers on Android 11 as they use our ble product.

**Expected behavior**

It's not known what causes the issue, but we expect the exception to be passed to our app, where we could take action there. Log the issue, disconnect etc.

**Smartphone :**
 - Device: A few from  OPPO, samsung, HUAWEI, Xiaomi 
 - OS: Android 11
 - Library version: 1.10.5

```
com.polidea.rxandroidble2.internal.SingleResponseOperation.timeoutFallbackProcedure (SingleResponseOperation.java:91)
com.polidea.rxandroidble2.internal.SingleResponseOperation.protectedRun (SingleResponseOperation.java:54)
com.polidea.rxandroidble2.internal.QueueOperation$1.subscribe (QueueOperation.java:41)
io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual (ObservableCreate.java:40)
io.reactivex.Observable.subscribe (Observable.java:12267)
io.reactivex.internal.operators.observable.ObservableUnsubscribeOn.subscribeActual (ObservableUnsubscribeOn.java:32)
io.reactivex.Observable.subscribe (Observable.java:12267)
com.polidea.rxandroidble2.internal.serialization.FIFORunnableEntry$1.run (FIFORunnableEntry.java:56)
io.reactivex.internal.schedulers.ScheduledDirectTask.call (ScheduledDirectTask.java:38)
io.reactivex.internal.schedulers.ScheduledDirectTask.call (ScheduledDirectTask.java:26)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:923) 
```
```

**Comment by dariuszseweryn** [comment]
The stack trace you included points to where the exception is being raised. Why do you think it is a library bug?

**Comment by sigurdurrafn** [comment]
Great, I'll then catch the bug and close this issue.

All I see are internal rx classes, where is the exception being raised so I can catch it?

**Comment by dariuszseweryn** [comment]
Do you have an error handler in each `.subscribe()` you wrote?
There is a slight chance for a race condition when disposing streams — in that case you can use `RxJavaPlugins.setErrorHandler()` (or similar) method

**Comment by sigurdurrafn** [comment]
Yes we handle all thrown exceptions, this happens despite that. That's why we reported this as a bug.
 
Is this race condition tracked ? 
I see https://github.com/Polidea/RxAndroidBle/issues/694 but seems to be a different issue.

Will add a global exception handler in any case, thanks.

**Comment by dariuszseweryn** [comment]
You haven't disclosed the source code that is expected to be handling the error nor you did not disclose the full stack trace and the exact exception message. There is #213 which is supposed to address the `UndeliverableException`. But if you have an uncaught exception then I would think that you lack an error handler in some `.subscribe()`

**Comment by dariuszseweryn** [comment]
Closing due to lack of information and inactivity of the original poster.

When more data will be available—feel free to add that information and reopen this issue.

Best Regards
