### ISSUE TITLE
Could it be possible port this library to Processing language?

### ISSUE THREAD

**Issue by q2dg** [Polidea/RxAndroidBle#85]
Maybe these links can help: https://github.com/processing/processing/wiki/Library-Basics and https://github.com/processing/processing/wiki/Library-Guidelines . Maybe this too: https://github.com/processing/processing-library-template

Thanks!!

**Comment by dariuszseweryn** [comment]
Hello,
I don't see a reason why it couldn't be possible. It should be possible. I hope that answers your question. :)
Best Regards
