### ISSUE TITLE
Change notification gets invoked out-of-order when receiving long string

### ISSUE THREAD

**Issue by cksss** [Polidea/RxAndroidBle#88]
### Summary
<br />Long contiguous string of at least 30-bytes will be sent in multiple fragments which would trigger change notification multiple times. The order at which the change notification gets invoked may not always be in the expected order.

#### Preconditions
<br />Unknown
#### Steps to reproduce actual result
<br />1.  Setup change notification on connected BLE device.

<p>
<br>   connectionObservable
<br>        .flatMap(rxBleConnection -> rxBleConnection.setupNotification(UUID.fromString(HM_RX_TX)))
<br>        .doOnNext(notificationObservable -> {
                        })
<br>        .flatMap(notificationObservable -> notificationObservable) 
<br>        .subscribe(this::onNotificationReceived,this::onReadFailure);
<br>
<br>    private void onNotificationReceived(byte[] bytes) {
<br>            String s = new String(bytes, "UTF-8");
<br>            StringBuilder sb = new StringBuilder(s);
<br>            Log.d(TAG, "[BLE_NOTIFICATION] "+s);
<br>    }
</p>

<br />2. Get BLE device to continuously send long string. The following code is used in Arduino with HM-10 BLE.
<p>
<br>loop {
<br>   String tmpint = String(idx);
<br>   String testBuff=tmpint+"_AAAAAAAAAABBBBBBBB_"+tmpint+"_CCCCCC";
<br>  Serial.println(testBuff);
<br>   idx++;
<br>   if(idx>99) {  idx=0; }
<br>  delay(500);
<br>}
</p>

<br />3. Observe the order of data reported by onNotificationReceived()

#### Actual result
<br />
<p>
<br>[BLE_NOTIFICATION] 9_AAAAAAAAAABBBBBBBB
<br>[BLE_NOTIFICATION] _9_CCCCCC
<br>[BLE_NOTIFICATION] 10_AAAAAAAAAABBBBBBB
<br>[BLE_NOTIFICATION] B_10_CCCCCC
<br>[BLE_NOTIFICATION] 11_AAAAAAAAAABBBBBBB
<br>[BLE_NOTIFICATION] B_11_CCCCCC
<br>[BLE_NOTIFICATION] 12_AAAAAAAAAABBBBBBB
<br>[BLE_NOTIFICATION] B_12_CCCCCC
<br>[BLE_NOTIFICATION] B_13_CCCCCC
<br>[BLE_NOTIFICATION] 13_AAAAAAAAAABBBBBBB
<br>[BLE_NOTIFICATION] 14_AAAAAAAAAABBBBBBB
<br>[BLE_NOTIFICATION] B_14_CCCCCC
<br>[BLE_NOTIFICATION] 15_AAAAAAAAAABBBBBBB
<br>[BLE_NOTIFICATION] B_15_CCCCCC
<br>[BLE_NOTIFICATION] 16_AAAAAAAAAABBBBBBB
<br>[BLE_NOTIFICATION] B_16_CCCCCC
<br>[BLE_NOTIFICATION] B_17_CCCCCC
<br>[BLE_NOTIFICATION] 17_AAAAAAAAAABBBBBBB
</p>

#### Expected result

<p>
<br>[BLE_NOTIFICATION] 9_AAAAAAAAAABBBBBBBB
<br>[BLE_NOTIFICATION] _9_CCCCCC
<br>[BLE_NOTIFICATION] 10_AAAAAAAAAABBBBBBB
<br>[BLE_NOTIFICATION] B_10_CCCCCC
<br>[BLE_NOTIFICATION] 11_AAAAAAAAAABBBBBBB
<br>[BLE_NOTIFICATION] B_11_CCCCCC
<br>[BLE_NOTIFICATION] 12_AAAAAAAAAABBBBBBB
<br>[BLE_NOTIFICATION] B_12_CCCCCC
<br>[BLE_NOTIFICATION] 13_AAAAAAAAAABBBBBBB
<br>[BLE_NOTIFICATION] B_13_CCCCCC
<br>[BLE_NOTIFICATION] 14_AAAAAAAAAABBBBBBB
<br>[BLE_NOTIFICATION] B_14_CCCCCC
<br>[BLE_NOTIFICATION] 15_AAAAAAAAAABBBBBBB
<br>[BLE_NOTIFICATION] B_15_CCCCCC
<br>[BLE_NOTIFICATION] 16_AAAAAAAAAABBBBBBB
<br>[BLE_NOTIFICATION] B_16_CCCCCC
<br>[BLE_NOTIFICATION] 17_AAAAAAAAAABBBBBBB
<br>[BLE_NOTIFICATION] B_17_CCCCCC
</p>

**Comment by dariuszseweryn** [comment]
Hello,
Thanks for your report. This issue was already mentioned here: https://github.com/Polidea/RxAndroidBle/issues/75 and is (should be) fixed in the main branch so you could try the SNAPSHOT release.
I plan to fix one more bug before making another official release.
Best Regards
