### ISSUE TITLE
The method scanBleDevices(UUID... filters) is not support for two types service. 

### ISSUE THREAD

**Issue by iBotasky** [Polidea/RxAndroidBle#91]
@nightscape Sorry I need help, I think this is not Bug. maybe!
I got a problem that the method scanBleDevices(UUID... filters) cannot support to discover double kind of devices with different UUIDServices. 

I guess  that the relationship between the args are AND, but not OR. But How could I get the double kind of device with different UUIDService?

The code is that i want to find out the device with the uuid ```00001801-0000-1000-8000-00805F9B34FB``` and another device with uuid ```6E400001-B5A3-F393-E0A9-E50E24DCCA9E``` , But i always cannot get the result with the code. 
```
scanScription = rxBleClient
                .scanBleDevices(UUID.fromString("00001801-0000-1000-8000-00805F9B34FB"),  UUID.fromString("6E400001-B5A3-F393-E0A9-E50E24DCCA9E"))
                .subscribe(new Action1<RxBleScanResult>() {
            @Override
            public void call(RxBleScanResult rxBleScanResult) {
                if (!bleDeviceHashMap.containsKey(rxBleScanResult.getBleDevice().getMacAddress())) {
                    bleDeviceHashMap.put(rxBleScanResult.getBleDevice().getMacAddress(), rxBleScanResult.getBleDevice());
                    HashMap<String, String> ble = new HashMap<String, String>();
                    ble.put("name", rxBleScanResult.getBleDevice().getName());
                    ble.put("address", rxBleScanResult.getBleDevice().getMacAddress());
                    bleDevices.add(ble);
                    adapter.notifyDataSetChanged();
                }
            }
        });
```

**Comment by dariuszseweryn** [comment]
Hello @iBotasky 
The feature works as intended. It has the same behaviour as default filtering in Android 4.3 and 4.4. There is a plan to update the scanning to use 5.0 features.
About how to implement the desired behaviour I encourage you to post a question on www.stackoverflow.com with tag `rxandroidble` so the knowledge will not be lost.
Best Regards

**Comment by iBotasky** [comment]
@dariuszseweryn OK，I got it ,Thanks for your help.
