### ISSUE TITLE
Butterknife 

### ISSUE THREAD

**Issue by R3n4rD** [Polidea/RxAndroidBle#96]
### Summary
When trying sample and activity1, butterknife does not generate/bind views.
<br />
#### Preconditions
Android Studio 2.2.2, N5X Android 7.0
<br />
#### Steps to reproduce actual result
1. Launch the project and the phone
2. RecyclerView will be null, crash
<br />
#### Correction
Adding not only dependencie but apply plugin should help gradle building classes i guess...
apply plugin: 'com.jakewharton.butterknife' **at the start of the project**
annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0' **(maybe not mandatory)**

I also added dependencies in buildscript, but probably
```
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'me.tatarka:gradle-retrolambda:3.3.1'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'
    }
}
```
<br />

**Comment by dariuszseweryn** [comment]
Thank you for the info. Fixed. 👍
